var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,e){if(d){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];f in b||(b[f]={});b=b[f]}a=a[a.length-1];e=b[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,b,e){var d=this.length||0;0>b&&(b=Math.max(0,d+b));if(null==e||e>d)e=d;e=Number(e);0>e&&(e=Math.max(0,d+e));for(b=Number(b||0);b<e;b++)this[b]=a;return this}},"es6-impl","es3");
updateResEvent=function(a){window.addEventListener("resize",function(d){a.width=window.innerWidth-20;a.height=window.innerHeight-20})};
var Score=function(a){void 0==a&&(a="#000FFF");this.coins=this.max=this.player=0;this.getMax=function(){this.max=getCookie("maxScore");0==this.max.length&&(document.cookie="maxScore = 0",this.max=getCookie("maxScore"));this.max=Number(this.max)};this.getCoins=function(){this.coins=getCookie("coins");0==this.coins.length&&(document.cookie="coins= 0",this.coins=getCookie("coins"));this.coins=Number(this.coins)};this.draw=function(a){ctx.beginPath();ctx.fillStyle=a;ctx.font="14px Arial";string="Score: "+
this.player;ctx.fillText(string,c.width/2-40,c.height-20);string="Max Score: "+this.max;ctx.fillText(string,c.width/2-160,c.height-20)}};
function generateAsteroids(a,d,b,e,f,g){for(i=0;i<f;i++)rect=new randomRect(a,d,b,e),rect.hp=Math.round(Math.sqrt(rect.mass)),rect.dead=!1,rect.sufferDamage=asteroidSufferDamage,rect.value=Math.round(rect.hp/40),objects.push(rect);for(i=0;i<g;i++)triangle=new randomTriangle(a,d,b,e),triangle.hp=Math.round(Math.sqrt(triangle.mass)),triangle.dead=!1,triangle.sufferDamage=asteroidSufferDamage,triangle.value=Math.round(triangle.hp/40),objects.push(triangle)}
function generateTurrets(a,d,b,e){b=void 0===b?!1:b;e=void 0===e?1:e;for(var f=0;f<a;f++){var g=Math.random()*c.width,h=Math.random()*c.height;myRandom=Math.random();.9<myRandom?(turret=new Turret("#FFFFFF","#FF0000",d,g,h,40,heavyLaserBlaster),turret.hitbox.spin=20):.8<myRandom?turret=Turret("#FFFFFF","#FF0000",d,g,h,40,asteroidShooter):.7<myRandom?turret=Turret("#FFFFFF","#FF0000",d,g,h,40,heavyCannon):.6<myRandom?(turret=new Turret("#FFFFFF","#FF0000",d,g,h,40,lightLaserBlaster),turret.hitbox.spin=
20):turret=.5<myRandom?Turret("#FFFFFF","#FF0000",d,g,h,40,lightCannon):Turret("#FFFFFF","#FF0000",d,g,h,40,machineGun);for(g=0;g<d;g++)turret.weapons[g].rateOfFire*=e,turret.weapons[g].setCenter(player.hitbox.center),turret.weapons[g].setPosition(turret.hitbox.vertices[g]),turret.weapons[g].firing=!0;turret.weapon.setOwner(turret);b&&(turret.engineOn=!0,rotatePolygon(turret.hitbox,360*Math.random()));turret.value=Math.round(10*myRandom);turret.value*=d;enemies.push(turret)}}
var Level=function(a){this.current=0;this.max=20;this.draw=function(a){ctx.beginPath();ctx.fillStyle=a;ctx.font="14px Arial";string="Level: "+this.current;ctx.fillText(string,c.width/2+40,c.height-20)};this.start=function(){player.setImmunity(3);12>=this.current?(player.hull.recover(10),0!=this.current%2?generateAsteroids(c.width/20+2*this.current,c.width/100+2*this.current,Math.round(.7*this.current),Math.floor(.2*this.current),Math.round(.6*this.current),Math.round(.4*this.current)):generateTurrets(Math.floor(this.current/
2),1,!0,.25)):13<=this.current&&15>=this.current?generateTurrets(Math.floor(this.current/3),2,!0,.5):generateTurrets(Math.floor(this.current/4),3,!0,.75)};this.next=function(){this.current++}},Game=function(){this.over=!1};
function buildInstructions(){var a=[];a.push("W: Main Engine Throttle");a.push("Q: Reverse Engine Throttle");a.push("A: Left turning");a.push("D: Right turning");a.push("Q: Left strafe");a.push("E: Right strafe");a.push("S: Advanced Braking System");a.push("Space: Shoot");a.push("X: Auto-Fire");a.push("R: Cycle Weapons");a.push("F: Enable Shield");a.push("Click: Auto-pilot to given point (locks down the ship)");return a}
function buildWeaponsStatus(a){for(var d=[],b=0;b<a.length;b++)string=a[b].enabled?a[b].name+": enabled":a[b].name+": disabled",a[b].hasAmmo&&(string+=" --- Ammo: "+a[b].ammo),d.push(string);return d}function drawWeaponsStatus(a,d){d=void 0===d?"#00F0FF":d;ctx.beginPath();ctx.fillStyle=d;ctx.font="14px Arial";for(var b=0,e=0;e<a.length;e++)0==e%3&&(b+=240),ctx.fillText(a[e],b-230,40+e%3*20)}
function drawInstructions(a,d){d=void 0===d?"#000FFF":d;ctx.beginPath();ctx.fillStyle=d;ctx.font="14px Arial";for(var b=0,e=0;e<a.length;e++)0==e%3&&(b+=240),ctx.fillText(a[e],b-230,40+e%3*20)}
function drawEndGame(a,d,b){d=void 0===d?"#000FFF":d;b=void 0===b?"#FF0000":b;a?(ctx.beginPath(),ctx.fillStyle=d,ctx.font="28px Arial",ctx.fillText("Congratulations! You've won! Press F5 to restart.",c.width/3,c.height/2)):(ctx.beginPath(),ctx.fillStyle=b,ctx.font="28px Arial",ctx.fillText("You've died! Press F5 to restart.",c.width/3,c.height/2))}
var Phases=function(){this.phase6=this.phase5=this.phase4=this.phase3=this.phase2=this.phase1=!1;this.current=0},EnergySource=function(a,d,b){b=void 0===b?500:b;this.current=this.max=void 0===a?100:a;this.rechargeRate=void 0===d?10:d;this.rechargeSpeed=b;this.rechargeEvent=void 0;this.recharging=!0;this.getValue=function(){var a=this.max*this.rechargeRate,a=a/1E3*(1E3-b);return a=Math.round(a)};this.describe=function(){var a=[];a.push("Max points: "+this.max,"Recharge Rate: "+this.rechargeRate,"Recharge Speed: "+
this.rechargeSpeed/1E3+" seconds");return a};this.recharge=function(a){this.recharging&&(this.current<this.max&&(this.current+=this.rechargeRate,this.current>this.max&&(this.current=this.max),this.recharging=!1,this.rechargeEvent=void 0),void 0==this.rechargeEvent&&(this.rechargeEvent=setTimeout(function(){a.recharging=!0},a.rechargeSpeed)))};this.drain=function(a){this.current-=a;0>this.current&&(this.current=0)}},Shield=function(a,d,b,e,f){this.enabled=!1;this.max=void 0===a?100:a;this.current=
0;this.drainRate=void 0===b?10:b;this.rechargeEfficiency=void 0===e?.5:e;this.drainSpeed=void 0===f?250:f;this.draining=!0;this.drainEvent=void 0;this.powerSupply=new EnergySource(0,0);this.resistance=0;this.resistanceType="f";this.getValue=function(){value=this.max*(this.resistance+1);value*=this.rechargeEfficiency;value*=1E3-this.drainSpeed;return value=Math.round(value/100)};this.describe=function(){var a=[];a.push("Max points: "+this.max,"Drain Rate: "+this.drainRate,"Recharge Efficiency: "+this.rechargeEfficiency,
"Drain Speed: "+this.drainSpeed/1E3+" seconds","Resistance: "+this.resistance);return a};this.setPowerSupply=function(a){this.powerSupply=a};this.setEnabled=function(a){this.enabled=a};this.drainEnergy=function(a){this.draining&&this.enabled&&(this.draining=!1,this.drainingEvent=void 0,void 0===this.drainingEvent&&(this.drainingEvent=setTimeout(function(){a.draining=!0},a.drainSpeed)),this.current<this.max&&(this.powerSupply.current>this.drainRate?(this.current+=this.drainRate*this.rechargeEfficiency,
this.powerSupply.current-=this.drainRate):(this.current+=this.powerSupply.current*this.rechargeEfficiency,this.powerSupply.current=0),this.current>this.max&&(this.current=this.max)))};this.sufferDamage=function(a){a="f"==this.resistanceType?a-this.resistance:a*this.resistance;0<a&&(this.current-=a);0>this.current?(a=-1*this.current,this.current=0):a=0;return a}},Hull=function(a,d){d=void 0===d?0:d;this.current=this.max=void 0===a?100:a;this.resistance=d;this.resistanceType="f";this.getValue=function(){return value=
this.max*(this.resistance+1)};this.describe=function(){var a=[];a.push("Max points: "+this.max,"Resistance: "+this.resistance);return a};this.sufferDamage=function(a){a="f"==this.resistanceType?a-d:a*d;0<a&&(this.current-=a)};this.recover=function(a){this.current+=a;this.current>this.max&&(this.current=this.max)}},Weapon=function(a,d,b,e,f,g,h,m,l,n,k){a=void 0===a?10:a;d=void 0===d?1:d;b=void 0===b?1E3:b;e=void 0===e?10:e;f=void 0===f?10:f;g=void 0===g?1:g;m=void 0===m?0:m;l=void 0===l?!1:l;n=void 0===
n?100:n;k=void 0===k?0:k;this.firing=this.enabled=this.turret=!1;this.rateOfFire=void 0===h?8:h;this.lockDown=!1;this.position=new Point(0,0);this.center=new Point(0,0);this.direction=new Vector(0,0);this.projectileVelocity=a;this.projectileWidth=d;this.range=b;this.limit=e;this.mass=g;this.damage=f;this.hasAmmo=l;this.energyUsage=k;this.ammo=l?n:1;0<k&&(this.powerSupply=new EnergySource(0,0));this.turnRate=0;this.projectileHeight=2*this.projectileVelocity;this.projectiles=[];this.setTurnRate=function(a){this.turnRate=
a};this.setTurretMode=function(a){this.turret=a};this.setOwner=function(a){this.owner=a};this.setPosition=function(a){this.position=a};this.setCenter=function(a){this.center=a};this.setPowerSupply=function(a){this.powerSupply=a};this.getValue=function(){var a;this.type="l";a=20*this.damage;a=this.hasAmmo?a-this.ammo/500:a-this.energyUsage;a-=this.limit;this.turret&&(a*=4);return Math.round(a)};this.updateDirection=function(){calculateVector(this.position,this.center,this.direction);unitVector(this.direction,
this.direction);this.turret&&(this.direction.x*=-1,this.direction.y*=-1)};this.updateFiring=function(a){if(!(this.projectiles.length>=this.limit||0==this.firing||1==this.lockDown||0>=this.ammo)){if(0<this.energyUsage){if(this.powerSupply.current<this.energyUsage)return;this.powerSupply.drain(k)}this.lockDown=!0;a=new Rect(this.position.x,this.position.y-this.projectileHeight/2,this.projectileWidth,this.projectileHeight,this.direction.x,this.direction.y,this.projectileVelocity+a,0);a.hit=!1;a.mass=
this.mass;a.duration=this.range/this.velocity;yAxis=new Vector(0,1);var b=angleVectors(this.direction,yAxis);this.turret?this.position.x<this.center.x&&(b*=-1):this.position.x>this.center.x&&(b*=-1);rotatePolygon(a,radiansToDegrees(b));a.spin=m;a.duration=this.range/this.projectileVelocity;this.projectiles.push(a);this.hasAmmo&&this.ammo--;this.resetLockDown(this)}};this.fire=function(a){this.firing=a};this.updateDuration=function(){for(var a=0;a<this.projectiles.length;a++)this.projectiles[a].duration--,
0>=this.projectiles[a].duration&&this.projectiles.splice(a,1)};this.autoFire=function(){this.firing=1==this.firing?!1:!0};this.resetLockDown=function(a){setTimeout(function(){a.lockDown=!1},1E3/this.rateOfFire)};this.rotateAtBorder=function(a,b){if("x"==a){rotatingVersor=new Vector(-b.versor.x,b.versor.y);var d=angleVectors(b.versor,rotatingVersor),d=radiansToDegrees(d);0<rotatingVersor.y&&(d*=-1);0<rotatingVersor.x&&(d*=-1)}else"y"==a&&(rotatingVersor=new Vector(b.versor.x,-b.versor.y),d=angleVectors(b.versor,
rotatingVersor),d=radiansToDegrees(d),0>rotatingVersor.x&&(d*=-1),0<rotatingVersor.y&&(d*=-1));rotatePolygon(b,d)};this.onHit=function(a){a.sufferDamage(this.damage)};this.removeProjectiles=function(){for(var a=0;a<this.projectiles.length;a++)1==this.projectiles[a].hit&&(this.projectiles.splice(a,1),a--)};this.draw=function(){this.drawCannon();if(void 0!=this.owner)for(var a=0;a<this.projectiles.length;a++)drawPolygon(this.projectiles[a],strokeColor=this.owner.primaryColor,hitColor=this.owner.secondaryColor,
joints=!0,center=!1,fillColor=this.owner.secondaryColor,centerColor=this.owner.secondaryColor,jointColor=this.owner.secondaryColor);else for(a=0;a<this.projectiles.length;a++)drawPolygon(this.projectiles[a])};this.drawCannon=function(a){a=void 0===a?"#000FFF":a;void 0!=this.owner&&(a=this.owner.secondaryColor);ctx.beginPath();ctx.lineWidth=2;ctx.strokeStyle=a;0==this.turret?(ctx.moveTo(this.center.x,this.center.y),ctx.lineTo(this.center.x+20*this.direction.x,this.center.y+20*this.direction.y)):(ctx.moveTo(this.position.x,
this.position.y),ctx.lineTo(this.position.x+20*this.direction.x,this.position.y+20*this.direction.y));ctx.stroke()}},Ship=function(a,d,b,e,f){e=void 0===e?"#0000FF":e;f=void 0===f?"#00F0FF":f;this.hitbox=new Triangle(a,d,b,0,0,0,0);this.primaryColor=e;this.secondaryColor=f;this.auxHitbox=new Triangle(a,d-b,b,0,0,0,0);this.powerSupply=new EnergySource(100,10);this.hull=new Hull;this.shield=new Shield;this.dead=this.immunity=!1;this.weapons=[];this.currentWeapon=0;this.isStrafing=this.isTurning=this.braking=
this.reverseEngine=this.engineOn=this.lock=!1;this.strafingSide=0;this.acceleration=.125;this.maxSpeed=4;this.turnRate=3.5;this.turning=!1;this.rotate=0;this.front=new Point(this.hitbox.vertices[2].x,this.hitbox.vertices[2].y);this.inertiaVector=new Vector(0,0);this.engineVersor=new Vector(0,0);this.engineVector=new Vector(0,0);this.strafingVector=new Vector(0,0);this.autoPath=new Point(0,0);this.getEngineValue=function(){var a=10*this.maxSpeed,a=a+1E3*this.acceleration,a=a+100*this.turnRate;return Math.round(a)};
this.describeEngine=function(){var a=[];a.push("Max Speed: "+this.maxSpeed,"Acceleration : "+this.acceleration,"Turn Rate: "+this.turnRate);return a};this.getValue=function(){for(var a=this.getEngineValue(),a=a+this.hull.getValue(),a=a+this.shield.getValue(),a=a+this.powerSupply.getValue(),b=0;b<this.weapons.length;b++)a+=this.weapons[b].getValue();return a};this.updateDirection=function(){if(this.engineOn||this.reverseEngineOn||0!=this.braking){this.inertiaVector.x=this.hitbox.versor.x*this.hitbox.velocity;
this.inertiaVector.y=this.hitbox.versor.y*this.hitbox.velocity;this.engineOn?(calculateVector(this.front,this.hitbox.center,this.engineVersor),unitVector(this.engineVersor,this.engineVersor),this.engineVector.x=this.engineVersor.x*this.acceleration,this.engineVector.y=this.engineVersor.y*this.acceleration):this.braking?(unitVector(this.inertiaVector,this.engineVersor),this.engineVersor.x*=-1,this.engineVersor.y*=-1,this.acceleration>this.hitbox.velocity?(this.engineVector.x=this.engineVersor.x*this.hitbox.velocity,
this.engineVector.y=this.engineVersor.y*this.hitbox.velocity):(this.engineVector.x=this.engineVersor.x*this.acceleration,this.engineVector.y=this.engineVersor.y*this.acceleration)):(calculateVector(this.front,this.hitbox.center,this.engineVersor),unitVector(this.engineVersor,this.engineVersor),this.reverseEngineOn&&(this.engineVersor.x*=-1,this.engineVersor.y*=-1,this.engineVector.x=this.engineVersor.x*this.acceleration,this.engineVector.y=this.engineVersor.y*this.acceleration));var a=new Vector(this.engineVector.x+
this.inertiaVector.x,this.engineVector.y+this.inertiaVector.y),b=norm(a);b<=this.maxSpeed?0==b?(this.hitbox.velocity=b,this.hitbox.versor.x=0,this.hitbox.versor.y=0):(unitVector(a,a),this.hitbox.velocity=b,this.hitbox.versor.x=a.x,this.hitbox.versor.y=a.y):(unitVector(a,a),this.hitbox.versor.x=a.x,this.hitbox.versor.y=a.y);this.auxHitbox.velocity=this.hitbox.velocity;this.auxHitbox.versor=this.hitbox.versor}};this.updatePosition=function(){this.hitbox.update();this.auxHitbox.update();this.front.x=
this.hitbox.vertices[2].x;this.front.y=this.hitbox.vertices[2].y};this.updateTurn=function(){if(this.isTurning){rotatePolygon(this.hitbox,this.rotate);theta=degreesToRadians(this.rotate);for(var b=0;b<this.auxHitbox.vertices.length;b++)this.auxHitbox.vertices[b].x-=this.hitbox.center.x,this.auxHitbox.vertices[b].y-=this.hitbox.center.y,a=this.auxHitbox.vertices[b].x*Math.cos(theta)-this.auxHitbox.vertices[b].y*Math.sin(theta),d=this.auxHitbox.vertices[b].x*Math.sin(theta)+this.auxHitbox.vertices[b].y*
Math.cos(theta),this.auxHitbox.vertices[b].x=a+this.hitbox.center.x,this.auxHitbox.vertices[b].y=d+this.hitbox.center.y}};this.turn=function(a,b){this.isTurning=b;this.rotate="l"==a?-this.turnRate:this.turnRate};this.updateStrafe=function(){if(this.isStrafing){this.inertiaVector.x=this.hitbox.versor.x*this.hitbox.velocity;this.inertiaVector.y=this.hitbox.versor.y*this.hitbox.velocity;var a=new midPoint(this.hitbox.vertices[0],this.hitbox.vertices[1]);-1==this.strafingSide?calculateVector(a,this.hitbox.vertices[0],
this.strafingVector):calculateVector(a,this.hitbox.vertices[1],this.strafingVector);unitVector(this.strafingVector,this.strafingVector);this.strafingVector.x=this.strafingVector.x*this.acceleration/3;this.strafingVector.y=this.strafingVector.y*this.acceleration/3;var a=new Vector(this.strafingVector.x+this.inertiaVector.x,this.strafingVector.y+this.inertiaVector.y),b=norm(a);b<=this.maxSpeed?0==b?(this.hitbox.velocity=b,this.hitbox.versor.x=0,this.hitbox.versor.y=0):(unitVector(a,a),this.hitbox.velocity=
b,this.hitbox.versor.x=a.x,this.hitbox.versor.y=a.y):(unitVector(a,a),this.hitbox.versor.x=a.x,this.hitbox.versor.y=a.y);this.auxHitbox.velocity=this.hitbox.velocity;this.auxHitbox.versor=this.hitbox.versor}};this.strafe=function(a,b){this.isStrafing=b;this.strafingSide="l"==a?1:-1};this.throttle=function(a){this.engineOn=a};this.brake=function(a){this.braking=a};this.reverseThrottle=function(a){this.reverseEngineOn=a};this.calculateAngle=function(a){pathVector=new Vector(0,0);frontVector=new Vector(0,
0);calculateVector(a,this.hitbox.center,pathVector);0==this.hitbox.velocity?(calculateVector(this.front,this.hitbox.center,frontVector),unitVector(frontVector,frontVector)):(frontVector.x=this.engineVersor.x,frontVector.y=this.engineVersor.y);translatedPoint=new Point(this.hitbox.center.x-a.x,this.hitbox.center.y-a.y);list=[];list.push(translatedPoint);rotatedVector=new Vector(0,0);a=degreesToRadians(90);rotatedVector.x=frontVector.x*Math.cos(a)-frontVector.y*Math.sin(a);rotatedVector.y=frontVector.x*
Math.sin(a)+frontVector.y*Math.cos(a);myProjection=projection(list,rotatedVector);this.pathAngle=angleVectors(frontVector,pathVector);this.pathAngle=radiansToDegrees(this.pathAngle);0<myProjection.min&&(this.pathAngle*=-1)};this.drawAutoPath=function(){this.lock&&(ctx.setLineDash([4]),ctx.strokeStyle=this.primaryColor,ctx.beginPath(),ctx.moveTo(this.hitbox.center.x,this.hitbox.center.y),ctx.lineTo(this.autoPath.x,this.autoPath.y),ctx.stroke(),ctx.setLineDash([0]))};this.autoRotate=function(){0!=this.pathAngle&&
(0<this.pathAngle?this.pathAngle>=this.turnRate?(this.pathAngle-=this.turnRate,this.turn("r",!0)):(this.turn("r",!0),this.updateTurn(),this.turn("l",!1),this.pathAngle=0):this.pathAngle<this.turnRate?(this.pathAngle+=this.turnRate,this.turn("l",!0)):(this.turn("l",!0),this.updateTurn(),this.turn("l",!1),this.pathAngle=0))};this.autoPilot=function(){this.lock&&(this.autoStatus.phase1?(this.calculateAngle(this.autoPath),this.autoStatus.phase1=!1,this.autoStatus.current++):this.autoStatus.phase2?(this.throttle(!1),
this.brake(!0),0==this.hitbox.velocity&&(this.autoStatus.phase2=!1,this.brake(!1),this.autoStatus.current++)):this.autoStatus.phase3?(this.calculateAngle(this.autoPath),this.autoStatus.phase3=!1):this.autoStatus.phase4?(this.autoRotate(),0==this.pathAngle&&(this.autoStatus.phase4=!1)):this.autoStatus.phase5?distance(this.hitbox.center,this.autoPath)/this.hitbox.velocity>this.hitbox.velocity/this.acceleration?this.throttle(!0):(this.autoStatus.phase5=!1,this.throttle(!1)):this.autoStatus.phase6&&(this.brake(!0),
0==this.hitbox.velocity&&(this.autoStatus.phase6=!1,this.brake(!1),this.lock=!1)))};this.autoStatus=new Phases;this.setupAutoPilot=function(a){this.autoPath=new Point(a.x,a.y);this.autoStatus.phase1=!0;this.autoStatus.phase2=!0;this.autoStatus.phase3=!0;this.autoStatus.phase4=!0;this.autoStatus.phase5=!0;this.autoStatus.phase6=!0;this.autoStatus.current=0};this.drawStatus=function(){ctx.beginPath();ctx.font="14px Arial";ctx.fillStyle=this.secondaryColor;string="Hull: "+this.hull.current;ctx.fillText(string,
c.width-200,30);string="Immunity: "+this.immunity;ctx.fillText(string,c.width-200,60);string="Energy: "+this.powerSupply.current;ctx.fillText(string,c.width-200,90);void 0!=this.shield&&(string=this.shield.enabled?"Shield enabled: "+this.shield.current:"Shield disabled: "+this.shield.current,ctx.fillText(string,c.width-200,120))};this.draw=function(a){a=void 0===a?this.hitbox:a;ctx.save();ctx.lineWidth=3;ctx.beginPath();1==a.hit&&0==this.shield.current?(ctx.strokeStyle="#FF0000",ctx.fillStyle="#FF0000"):
(ctx.strokeStyle=this.primaryColor,ctx.fillStyle=this.primaryColor);for(var b=0;b<a.vertices.length;b++)ctx.beginPath(),ctx.arc(a.vertices[b].x,a.vertices[b].y,3,0,2*Math.PI),2==b&&(ctx.fillStyle=this.secondaryColor),ctx.fill();for(b=0;b<a.vertices.length-1;b++)ctx.beginPath(),ctx.moveTo(a.center.x,a.center.y),ctx.lineTo(a.vertices[b].x,a.vertices[b].y),ctx.stroke();for(b=0;b<a.vertices.length-1;b++)ctx.beginPath(),ctx.moveTo(a.vertices[2].x,a.vertices[2].y),ctx.lineTo(a.vertices[b].x,a.vertices[b].y),
ctx.stroke();void 0!=a.center&&(ctx.fillStyle=this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,3,0,2*Math.PI),ctx.fill());1==this.immunity&&(ctx.strokeStyle=this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,a.side+2,0,2*Math.PI),ctx.stroke());this.shield.enabled&&0<this.shield.current&&(ctx.save(),ctx.strokeStyle=1==a.hit?this.primaryColor:this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,a.side+2,0,2*Math.PI),ctx.stroke(),ctx.restore());ctx.restore()};
this.setImmunity=function(a){this.immunity=!0;setTimeout(function(){this.player.immunity=!1},1E3*a)};this.addWeapon=function(a){this.weapons.push(a)};this.changeWeapon=function(){this.weapons[this.currentWeapon].firing=!1;this.currentWeapon++;this.currentWeapon%=this.weapons.length;this.weapon=this.weapons[this.currentWeapon]};this.cycleEnabledWeapons=function(){this.currentWeapon++;this.currentWeapon%=this.weapons.length;this.weapons[this.currentWeapon].enabled=this.weapons[this.currentWeapon].enabled?
!1:!0};this.sufferDamage=function(a){1!=this.immunity&&(void 0!=this.shield&&this.shield.enabled&&0<this.shield.current?(a=this.shield.sufferDamage(a))&&this.hull.sufferDamage(a):this.hull.sufferDamage(a),0>this.hull.current&&(this.dead=!0))}};function killObjects(a){for(i=0;i<a.length;i++)1==a[i].dead&&(score.player+=a[i].value,a.splice(i,1))}
function drawAsteroid(a,d,b){d=void 0===d?"#FFFFFF":d;b=void 0===b?"#FF0000":b;ctx.save();ctx.beginPath();ctx.lineWidth=3;ctx.strokeStyle=1==a.hit?b:d;ctx.moveTo(a.vertices[0].x,a.vertices[0].y);for(d=0;d<a.vertices.length;d++)ctx.lineTo(a.vertices[d].x,a.vertices[d].y);ctx.lineTo(a.vertices[0].x,a.vertices[0].y);ctx.stroke();ctx.restore()}function asteroidSufferDamage(a){this.hp-=a;0>this.hp&&(this.dead=!0)}
function drawHeavyBlaster(a,d,b,e,f,g,h){d=void 0===d?"#0000FF":d;b=void 0===b?"#FF0000":b;e=void 0===e?!0:e;f=void 0===f?!0:f;g=void 0===g?"#00F0FF":g;h=void 0===h?"#0000FF":h;ctx.save();ctx.beginPath();ctx.lineWidth=4;ctx.strokeStyle=1==a.hit?b:d;ctx.moveTo(a.vertices[0].x,a.vertices[0].y);ctx.lineTo(a.vertices[3].x,a.vertices[3].y);ctx.moveTo(a.vertices[1].x,a.vertices[1].y);ctx.lineTo(a.vertices[2].x,a.vertices[2].y);ctx.stroke();ctx.fillStyle=h;if(e)for(d=0;d<a.vertices.length;d++)ctx.beginPath(),
ctx.arc(a.vertices[d].x,a.vertices[d].y,3,0,2*Math.PI),ctx.fill();f&&void 0!=a.center&&(ctx.fillStyle=g,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,3,0,2*Math.PI),ctx.fill());ctx.restore()}function machineGun(){cannon=new Weapon(velocity=8,width=1,range=500,limit=12,damage=6,mass=100,rateOfFire=16,spin=0,hasAmmo=!0,ammo=2E3);cannon.type="p";cannon.name="Machine Gun";return cannon}
function lightCannon(){cannon=new Weapon(velocity=2,width=4,range=500,limit=10,damage=10,mass=100,rateOfFire=8,spin=120,hasAmmo=!0,ammo=1E3);cannon.projectileVelocity=10;cannon.type="p";cannon.name="Light Cannon";return cannon}function heavyCannon(){cannon=new Weapon(velocity=4,width=8,range=500,limit=10,damage=20,mass=1E3,rateOfFire=4,spin=120,hasAmmo=!0,ammo=500);cannon.projectileVelocity=10;cannon.type="p";cannon.name="Heavy Cannon";return cannon}
function asteroidShooter(){cannon=new Weapon(velocity=10,width=20,range=500,limit=1,damage=50,mass=1E4,rateOfFire=1,spin=120,hasAmmo=!0,ammo=50);cannon.projectileVelocity=10;cannon.type="p";cannon.name="Asteroid Shooter";return cannon}
function lightLaserBlaster(){blaster=new Weapon(velocity=30,width=1,range=1E3,limit=12,damage=5,mass=1,rateOfFire=12,spin=0,hasAmmo=!1,ammo=1,energyUsage=5);blaster.type="p";blaster.draw=function(){void 0!=this.owner&&(color=this.owner.secondaryColor,ctx.beginPath(),ctx.lineWidth=2,ctx.strokeStyle=color,0==this.turret?(ctx.moveTo(this.center.x,this.center.y),ctx.lineTo(this.center.x+20*this.direction.x,this.center.y+20*this.direction.y)):(ctx.moveTo(this.position.x,this.position.y),ctx.lineTo(this.position.x+
20*this.direction.x,this.position.y+20*this.direction.y)),ctx.stroke());if(void 0==blaster.owner)for(var a=0;a<this.projectiles.length;a++)drawPolygon(this.projectiles[a],strokeColor="#0000FF",hitColor="#0FF0FF",joints=!1,center=!1,fillColor="#0F00FF");else for(a=0;a<this.projectiles.length;a++)drawPolygon(this.projectiles[a],strokeColor=this.owner.primaryColor,hitColor=this.owner.secondaryColor,joints=!1,center=!1,fillColor="#0F00FF")};blaster.name="Light Laser Blaster";return blaster}
function heavyLaserBlaster(){blaster=new Weapon(velocity=30,width=12,range=1E3,limit=8,damage=20,mass=1,rateOfFire=6,spin=0,hasAmmo=!1,ammo=1,energyUsage=20);blaster.type="p";blaster.draw=function(){void 0!=this.owner&&(color=this.owner.secondaryColor,ctx.beginPath(),ctx.lineWidth=this.projectileWidth,ctx.strokeStyle=color,0==this.turret?(ctx.moveTo(this.center.x,this.center.y),ctx.lineTo(this.center.x+20*this.direction.x,this.center.y+20*this.direction.y)):(ctx.moveTo(this.position.x,this.position.y),
ctx.lineTo(this.position.x+20*this.direction.x,this.position.y+20*this.direction.y)),ctx.stroke());if(void 0==blaster.owner)for(var a=0;a<this.projectiles.length;a++)drawHeavyBlaster(this.projectiles[a],strokeColor="#0000FF",hitColor="#0FF0FF",joints=!1,center=!1,fillColor="#0F00FF");else for(a=0;a<this.projectiles.length;a++)drawHeavyBlaster(this.projectiles[a],strokeColor=this.owner.primaryColor,hitColor=this.owner.secondaryColor,joints=!1,center=!1,fillColor="#0F00FF")};blaster.name="Heavy Laser Blaster";
return blaster}
function lightLaserBeam(){beam=new Weapon(velocity=100,width=2,range=2E3,limit=1,damage=1,mass=1,rateOfFire=1E3,spin=0,hasAmmo=!1,ammo=1,energyUsage=4);beam.type="l";beam.draw=function(){ctx.beginPath();ctx.strokeStyle=void 0==this.owner?"#009099":this.owner.secondaryColor;oldWidth=ctx.lineWidth;ctx.lineWidth=this.projectileWidth;for(var a=0;a<this.projectiles.length;a++)ctx.moveTo(this.position.x,this.position.y),ctx.lineTo(this.projectiles[a].vertices[3].x,this.projectiles[a].vertices[3].y);ctx.stroke();
ctx.lineWidth=oldWidth};beam.name="Light Laser Beam";return beam}
function heavyLaserBeam(){beam=new Weapon(velocity=100,width=8,range=2E3,limit=1,damage=5,mass=1,rateOfFire=60,spin=0,hasAmmo=!1,ammo=1,energyUsage=9);beam.type="l";beam.draw=function(){ctx.strokeStyle=void 0==blaster.owner?"#009099":this.owner.secondaryColor;ctx.beginPath();oldWidth=ctx.lineWidth;ctx.lineWidth=beam.projectileWidth;for(var a=0;a<this.projectiles.length;a++)ctx.moveTo(this.position.x,this.position.y),ctx.lineTo(this.projectiles[a].vertices[3].x,this.projectiles[a].vertices[3].y);ctx.stroke();
ctx.lineWidth=oldWidth};beam.name="Heavy Laser Beam";return beam}function killProjectile(a){a.duration=0}
var Stellar=function(a,d){var b=new Ship(c.width/2,c.height/2,20,void 0===a?"#000FFF":a,void 0===d?"#0FF0FF":d);b.name="Stellar";b.updateDirection();b.hull=new Hull(100,0);b.shield=new Shield(50,0,5,1,300);b.acceleration=.21;b.turnRate=5;b.shield.setPowerSupply(b.powerSupply);b.shield.setEnabled(!0);b.addWeapon(machineGun());b.changeWeapon();b.weapon.setOwner(b);b.weapon.setCenter(b.hitbox.vertices[0]);b.weapon.setPosition(b.auxHitbox.vertices[0]);b.weapon.enabled=!0;b.addWeapon(machineGun());b.changeWeapon();
b.weapon.setOwner(b);b.weapon.setCenter(b.hitbox.vertices[1]);b.weapon.setPosition(b.auxHitbox.vertices[1]);b.weapon.enabled=!0;b.addWeapon(lightLaserBlaster());b.changeWeapon();b.weapon.setOwner(b);b.weapon.setPowerSupply(b.powerSupply);b.weapon.setPosition(b.hitbox.center);b.weapon.setCenter(coord);b.weapon.setTurretMode(!0);b.weapon.enabled=!0;return b},Gargatuan=function(a,d){var b=new Ship(c.width/2,c.height/2,50,void 0===a?"#0000FF":a,void 0===d?"#0FF0FF":d);b.name="Gargatuan";b.updateDirection();
b.hull=new Hull(200,1);b.shield=new Shield(300,0,20,.5,300);b.powerSupply=new EnergySource(1E3,20,100);b.shield.setPowerSupply(b.powerSupply);b.shield.setEnabled(!0);b.acceleration=.08;b.maxSpeed=7;b.turnRate=2;b.addWeapon(heavyLaserBlaster());b.changeWeapon();b.weapon.setOwner(b);b.weapon.setPowerSupply(b.powerSupply);b.weapon.setCenter(b.hitbox.vertices[0]);b.weapon.setPosition(b.auxHitbox.vertices[0]);b.weapon.enabled=!0;b.addWeapon(heavyLaserBlaster());b.changeWeapon();b.weapon.setOwner(b);b.weapon.setCenter(b.hitbox.vertices[1]);
b.weapon.setPosition(b.auxHitbox.vertices[1]);b.weapon.setPowerSupply(b.powerSupply);b.weapon.enabled=!0;b.addWeapon(heavyLaserBeam());b.changeWeapon();b.weapon.setOwner(b);b.weapon.setPowerSupply(b.powerSupply);b.weapon.setPosition(b.front);b.weapon.setCenter(b.hitbox.center);b.weapon.enabled=!0;return b},Colossal=function(a,d){var b=new Ship(c.width/2,c.height/2,100,void 0===a?"#0000FF":a,void 0===d?"#0FF0FF":d);b.name="Colossal";b.updateDirection();b.hull=new Hull(1E3,1);b.shield=new Shield(2E3,
0,50,1,150);b.powerSupply=new EnergySource(2E3,20,100);b.shield.setPowerSupply(b.powerSupply);b.shield.setEnabled(!0);b.acceleration=.04;b.maxSpeed=9;b.turnRate=1;for(var e=0;e<b.hitbox.vertices.length;e++)b.addWeapon(heavyLaserBlaster()),b.changeWeapon(),b.weapon.setOwner(b),b.weapon.setPowerSupply(b.powerSupply),b.weapon.setCenter(b.hitbox.vertices[e]),b.weapon.setPosition(b.auxHitbox.vertices[e]),b.weapon.enabled=!0;for(e=0;e<b.hitbox.vertices.length;e++)b.addWeapon(lightLaserBlaster()),b.changeWeapon(),
b.weapon.setOwner(b),b.weapon.setPowerSupply(b.powerSupply),b.weapon.setCenter(coord),b.weapon.setPosition(b.hitbox.vertices[e%3]),b.weapon.setTurretMode(!0),b.weapon.enabled=!0;return b},Turret=function(a,d,b,e,f,g,h){b=void 0===b?1:b;e=void 0===e?c.width/2:e;f=void 0===f?c.height/2:f;h=void 0===h?machineGun:h;a=new Ship(e,f,void 0===g?15:g,void 0===a?"#0000FF":a,void 0===d?"#0FF0FF":d);a.name="Turret";a.updateDirection();a.hull=new Hull(50,3);a.shield=new Shield(20,0,5,.5,300);a.powerSupply=new EnergySource(500,
10,100);a.shield.setPowerSupply(a.powerSupply);a.shield.setEnabled(!0);a.acceleration=.08;a.maxSpeed=3;a.turnRate=3;if(1==b)a.addWeapon(h()),a.changeWeapon(),a.weapon.setOwner(a),a.weapon.setPowerSupply(a.powerSupply),a.weapon.setCenter(coord),a.weapon.setPosition(a.hitbox.center),a.weapon.setTurretMode(!0),a.weapon.enabled=!0;else for(d=0;d<b;d++)a.addWeapon(h()),a.changeWeapon(),a.weapon.setOwner(a),a.weapon.setPowerSupply(a.powerSupply),a.weapon.setCenter(coord),a.weapon.setPosition(a.hitbox.vertices[d%
3]),a.weapon.setTurretMode(!0),a.weapon.enabled=!0;a.draw=function(a){a=void 0===a?this.hitbox:a;ctx.save();ctx.lineWidth=3;ctx.beginPath();1==a.hit&&0==this.shield.current?(ctx.strokeStyle="#FF0000",ctx.fillStyle="#FF0000"):(ctx.strokeStyle=this.primaryColor,ctx.fillStyle=this.primaryColor);for(var b=0;b<a.vertices.length;b++)ctx.beginPath(),ctx.moveTo(a.center.x,a.center.y),ctx.lineTo(a.vertices[b].x,a.vertices[b].y),ctx.stroke();for(b=0;b<a.vertices.length;b++)ctx.beginPath(),ctx.arc(a.vertices[b].x,
a.vertices[b].y,3,0,2*Math.PI),2==b&&(ctx.fillStyle=this.secondaryColor),ctx.fill();void 0!=a.center&&(ctx.fillStyle=this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,3,0,2*Math.PI),ctx.fill());1==this.immunity&&(ctx.strokeStyle=this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,a.side+2,0,2*Math.PI),ctx.stroke());this.shield.enabled&&0<this.shield.current&&(ctx.save(),ctx.strokeStyle=1==a.hit?this.primaryColor:this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,
a.center.y,a.side+2,0,2*Math.PI),ctx.stroke(),ctx.restore());ctx.restore()};return a};function fetchShipByName(a){if("Stellar"==a)var d=new Stellar;else"Gargatuan"==a?d=new Gargatuan:"Colossal"==a?d=new Colossal:"Turret"==a&&(d=new Turret("#000FFF","#00F0FF",3,c.width/2,c.height/2,20,lightLaserBlaster));return d}ctx.lineWidth=3;var j=0,lastDate=new Date,fps=new Fps,maxFPS=1E3,interval=1E3/maxFPS,COLLISION_DAMAGE=10,score=new Score;score.getMax();score.getCoins();
var level=new Level,instructions=buildInstructions(),objects=[],enemies=[],Button=function(a,d,b,e,f){this.x=a;this.y=d;this.width=b;this.height=e;this.string=void 0===f?" ":f;this.bgColor="#FFFFFF";this.fontColor="#000000";this.onClick=function(){console.log(this.string)};this.onHover=function(){this.bgColor="#666666"};this.draw=function(){ctx.fillStyle=this.bgColor;ctx.fillRect(this.x,this.y,this.width,this.height);ctx.fillStyle=this.fontColor;ctx.font="14px arial";ctx.fillText(this.string,this.x+
this.width/10,this.y+this.height/2)};this.reset=function(){this.bgColor="#FFFFFF"}},CircularButton=function(a,d,b,e,f){this.x=a;this.y=d;this.radius=b;this.color=e;this.string=f;this.onClick=function(){console.log(this.string)};this.draw=function(){ctx.fillStyle=this.color;ctx.beginPath();ctx.arc(this.x,this.y,this.radius,0,2*Math.PI);ctx.fill();ctx.fillStyle="#000000";ctx.font="14px arial";ctx.fillText(f,this.x-this.radius/6,this.y+this.radius/10)}};
function drawLobbyBackground(){ctx.fillStyle="#000000";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#FFFFFF";ctx.font="28px arial";ctx.fillText("Select your ship",20,40)}var buttons=[];myButton=new Button(20,200,150,50,"Stellar");myButton.onClick=function(){player=new Stellar;selected=!0;describeShipConsole(player)};buttons.push(myButton);myButton=new Button(20,260,150,50,"Gargatuan");myButton.onClick=function(){player=new Gargatuan;selected=!0;describeShipConsole(player)};buttons.push(myButton);
myButton=new Button(20,320,150,50,"Turret");myButton.onClick=function(){player=new Turret("#000FFF","#00F0FF",3,c.width/2,c.height/2,20,lightLaserBlaster);selected=!0;describeShipConsole(player)};buttons.push(myButton);myButton=new Button(20,380,150,50,"Colossal");myButton.onClick=function(){player=new Colossal;selected=!0;describeShipConsole(player)};buttons.push(myButton);myButton=new Button(20,100,200,50,"Coins: "+score.coins);myButton.onHover=function(){};buttons.push(myButton);
var coord=new Point(c.width/2,c.height/2),values=[];values.push(new Stellar);values.push(new Gargatuan);values.push(new Turret("#000FFF","#00F0FF",3,c.width/2,c.height/2,20,lightLaserBlaster));values.push(new Colossal);for(var i=1;i<values.length;i++)buttons[i].string+=": "+values[i].getValue();values=[];confirmButton=new Button(c.width/2-100,c.height-100,200,50,"Confirm");confirmButton.onClick=function(){"Stellar"==player.name&&(confirmed=!0);score.coins>player.getValue()&&(confirmed=!0)};
var instruct=!1,game=new Game,selected=!1,displaying=!1,confirmed=!1;
function selectShipLoop(){drawLobbyBackground();selected&&(displaying||(buttons.push(confirmButton),displaying=!0),displayShip(player),drawStats(player));for(var a=0;a<buttons.length;a++)buttons[a].draw();confirmed?(c.removeEventListener("touchstart",buttonModeClick,!1),c.removeEventListener("click",function(a){buttonModeClick(a)},!1),c.addEventListener("click",function(a){mouseClick(a)},!1),c.addEventListener("touchstart",pegaCoordenadasMobile,!1),buttons=[],displayValueConsole(player),c.width=window.innerWidth-
20,c.height=window.innerHeight-20,updateResEvent(c),console.log(fetchShipByName("Stellar")),player=fetchShipByName(player.name),requestAnimationFrame(mainLoop)):requestAnimationFrame(selectShipLoop)}
function displayValueConsole(a){console.log("engine: "+a.getEngineValue());console.log("hull:"+a.hull.getValue());console.log("shield:"+a.shield.getValue());console.log("power source:"+a.powerSupply.getValue());console.log("Weapons");for(var d=0;d<a.weapons.length;d++)console.log(a.weapons[d].name+": "+a.weapons[d].getValue());console.log("ship total: "+a.getValue())}
function describeShipConsole(a){console.log(a.name);var d;d="Shield --"+JSON.stringify(a.shield.describe());console.log(d);d="Hull--"+JSON.stringify(a.hull.describe());console.log(d);d="Energy Source--"+JSON.stringify(a.powerSupply.describe());console.log(d);d="Engine--"+JSON.stringify(a.describeEngine());console.log(d)}
function drawStats(a){ctx.save();ctx.beginPath();ctx.fillStyle="#FFFFFF";ctx.fillRect(c.width/3-20,20,c.width/1.5,c.height/4);ctx.fillStyle="#000000";ctx.font="11px arial";for(var d="Hull--"+JSON.stringify(a.hull.describe()),b=0;10>b;b++)d=d.replace('"',"");ctx.fillText(d,c.width/3,40);d="Engine--"+JSON.stringify(a.describeEngine());for(b=0;10>b;b++)d=d.replace('"',"");ctx.fillText(d,c.width/3,70);d="Energy Source--"+JSON.stringify(a.powerSupply.describe());for(b=0;10>b;b++)d=d.replace('"',"");ctx.fillText(d,
c.width/3,100);ctx.font="10px arial";var d;d="Shield --"+JSON.stringify(a.shield.describe());for(b=0;10>b;b++)d=d.replace('"',"");ctx.fillText(d,c.width/3,130);ctx.restore()}
function displayShip(a){a.draw();a.updateDirection();a.updateStrafe();a.updatePosition();a.updateTurn();a.powerSupply.recharge(a.powerSupply);a.shield.drainEnergy(a.shield);for(var d=0;d<a.weapons.length;d++)a.weapons[d].firing=!0,a.weapons[d].updateDirection(),a.weapons[d].enabled&&a.weapons[d].updateFiring(a.hitbox.velocity);for(d=0;d<a.weapons.length;d++)a.weapons[d].updateDuration(),a.weapons[d].removeProjectiles();for(b=0;b<a.weapons.length;b++)for(d=0;d<a.weapons[b].projectiles.length;d++)a.weapons[b].projectiles[d].update(),
projectile=a.weapons[b].projectiles[d],checkBorder(projectile)&&killProjectile(projectile),rotatePolygon(a.weapons[b].projectiles[d],a.weapons[b].projectiles[d].spin);for(var b=0;b<a.weapons.length;b++)for(d=0;d<a.weapons[b].projectiles.length;d++)calculateAxes(a.weapons[b].projectiles[d]),a.weapons[b].draw()}
function updateEnemy(a){var d=[];d.push(player);a.updateDirection();a.updateStrafe();a.updatePosition();a.updateTurn();a.powerSupply.recharge(a.powerSupply);a.shield.drainEnergy(a.shield);for(var b=0;b<a.weapons.length;b++)a.weapons[b].updateDirection(),a.weapons[b].enabled&&a.weapons[b].updateFiring(a.hitbox.velocity);for(var e=0;e<a.weapons.length;e++)for(b=0;b<a.weapons[e].projectiles.length;b++){calculateAxes(a.weapons[e].projectiles[b]);for(var f=0;f<objects.length;f++)smartCollision(a.weapons[e].projectiles[b],
objects[f],function(){a.weapons[e].onHit(objects[f])});smartCollision(a.weapons[e].projectiles[b],d[0].hitbox,function(){a.weapons[e].onHit(d[0])})}checkBorder(a.hitbox,function(){a.auxHitbox.applyVector(diff);a.engineOn?(a.engineOn=!1,a.reverseEngineOn=!0):(a.engineOn=!0,a.reverseEngineOn=!1)});calculateAxes(a.hitbox);rotatePolygon(a.hitbox,a.hitbox.spin);for(b=0;b<objects.length;b++)if(mtv=collisionSTA(a.hitbox,objects[b]))elasticCollision(a.hitbox,mtv,objects[b]),elasticCollision(a.auxHitbox,mtv,
objects[b]),a.sufferDamage(COLLISION_DAMAGE);for(e=0;e<a.weapons.length;e++)a.weapons[e].draw();for(b=0;b<a.weapons.length;b++)a.weapons[b].updateDuration(),a.weapons[b].removeProjectiles();for(e=0;e<a.weapons.length;e++)for(var g=0;g<a.weapons[e].projectiles.length;g++)a.weapons[e].projectiles[g].update(),"p"==a.weapons[e].type?checkBorder(a.weapons[e].projectiles[g],function(){a.weapons[e].rotateAtBorder(axis,a.weapons[e].projectiles[g])}):"l"==a.weapons[e].type&&(projectile=a.weapons[e].projectiles[g],
checkBorder(projectile)&&killProjectile(projectile)),rotatePolygon(a.weapons[e].projectiles[g],a.weapons[e].projectiles[g].spin)}
function mainLoop(){newDate=new Date;elapsedTime=newDate-lastDate;lastDate=new Date;fps.add(elapsedTime);ctx.fillStyle="#000000";ctx.fillRect(0,0,c.width,c.height);instruct?drawInstructions(instructions,player.secondaryColor):(weaponStatus=buildWeaponsStatus(player.weapons),drawWeaponsStatus(weaponStatus,player.secondaryColor));0==objects.length&&0==enemies.length&&level.current<=level.max&&(level.next(),level.current<=level.max&&level.start());for(var a=0;a<objects.length;a++)objects[a].update(),
checkBorder(objects[a]),calculateAxes(objects[a]),rotatePolygon(objects[a],objects[a].spin);if(player.dead)drawEndGame(!1),score.max<score.player&&(document.cookie="maxScore = "+score.player),score.coins=50*score.player,document.cookie="coins = "+score.coins;else{player.updateDirection();player.updateStrafe();player.updatePosition();player.updateTurn();player.powerSupply.recharge(player.powerSupply);player.shield.drainEnergy(player.shield);for(a=0;a<player.weapons.length;a++)player.weapons[a].updateDirection(),
player.weapons[a].enabled&&player.weapons[a].updateFiring(player.hitbox.velocity);for(a=0;a<enemies.length;a++)updateEnemy(enemies[a]);for(var d=0;d<player.weapons.length;d++)for(a=0;a<player.weapons[d].projectiles.length;a++){calculateAxes(player.weapons[d].projectiles[a]);for(var b=0;b<objects.length;b++)smartCollision(player.weapons[d].projectiles[a],objects[b],function(){player.weapons[d].onHit(objects[b])});for(var e=0;e<enemies.length;e++)smartCollision(player.weapons[d].projectiles[a],enemies[e].hitbox,
function(){player.weapons[d].onHit(enemies[e])})}checkBorder(player.hitbox,function(){player.auxHitbox.applyVector(diff)});calculateAxes(player.hitbox);rotatePolygon(player.hitbox,player.hitbox.spin)}level.current>level.max&&drawEndGame(!0);for(a=0;a<objects.length;a++)if(mtv=collisionSTA(player.hitbox,objects[a]))elasticCollision(player.hitbox,mtv,objects[a]),elasticCollision(player.auxHitbox,mtv,objects[a]),player.sufferDamage(COLLISION_DAMAGE);for(a=0;a<enemies.length;a++)if(mtv=collisionSTA(player.hitbox,
enemies[a].hitbox))elasticCollision(player.hitbox,mtv,enemies[a].hitbox),elasticCollision(player.auxHitbox,mtv,enemies[a].hitbox),player.sufferDamage(COLLISION_DAMAGE);for(d=0;d<player.weapons.length;d++)player.weapons[d].draw();for(a=0;a<player.weapons.length;a++)player.weapons[a].updateDuration(),player.weapons[a].removeProjectiles();for(d=0;d<player.weapons.length;d++)for(e=0;e<player.weapons[d].projectiles.length;e++)player.weapons[d].projectiles[e].update(),"p"==player.weapons[d].type?checkBorder(player.weapons[d].projectiles[e],
function(){player.weapons[d].rotateAtBorder(axis,player.weapons[d].projectiles[e])}):"l"==player.weapons[d].type&&(projectile=player.weapons[d].projectiles[e],checkBorder(projectile)&&killProjectile(projectile)),rotatePolygon(player.weapons[d].projectiles[e],player.weapons[d].projectiles[e].spin);player.autoPilot();player.drawStatus();for(a=0;a<objects.length;a++)drawAsteroid(objects[a]);for(a=0;a<enemies.length;a++)enemies[a].draw();0==player.dead&&(player.drawAutoPath(),player.draw());killObjects(objects);
killObjects(enemies);checkColisionsNaive(objects);score.draw(player.secondaryColor);level.draw(player.secondaryColor);fps.calculateMean();drawFPS(fps.mean,player.secondaryColor);setTimeout(function(){requestAnimationFrame(mainLoop)},interval)}function getCookie(a){a+="=";for(var d=decodeURIComponent(document.cookie).split(";"),b=0;b<d.length;b++){for(var e=d[b];" "==e.charAt(0);)e=e.substring(1);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return""}
function setCookie(a,d,b){var e=new Date;e.setTime(e.getTime()+864E5*b);b="expires="+e.toUTCString();document.cookie=a+"="+d+";"+b+";path=/"}var deleteCookie=function(a){document.cookie=a+"=;expires=Thu, 01 Jan 1970 00:00:01 GMT;"};console.log(document.cookie);selectShipLoop();
