<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> <!--320-->
</head>
<body>
<canvas id="umCanvas" width="800" height="600">
<audio id="selectLoop">
<source src="selectLoop.mp3" type ="audio/mpeg">
</audio>
<audio id="loopA">
<source src="loopA.mp3" type ="audio/mpeg">
</audio>
<audio id="machineGun">
<source src="soundEffects/machine_gun.mp3" type ="audio/mpeg">
</audio>
<audio id="lightLaser">
<source src="Laser_Shoot.mp3" type ="audio/mpeg">
</audio>
<audio id="heavyLaser">
<source src="Laser_Shoot2.mp3" type ="audio/mpeg">
</audio>
<audio id="heavyCannon">
<source src="heavycannon.mp3" type ="audio/mpeg">
</audio>
<audio id="laserBeam">
<source src="laser-reapeated.mp3" type ="audio/mpeg">
</audio>
<audio id="explosion">
<source src="Explosion4.mp3" type ="audio/mpeg">
</audio>
<audio id="hurt">
<source src="Hit_Hurt5.mp3" type ="audio/mpeg">
</audio>
<audio id="explosionLong">
<source src="Explosion4_long_engine.mp3" type ="audio/mpeg">
</audio>
 
<script> 
var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var g=a[e];g in d||(d[g]={});d=d[g]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,d,e){var b=this.length||0;0>d&&(d=Math.max(0,b+d));if(null==e||e>b)e=b;e=Number(e);0>e&&(e=Math.max(0,b+e));for(d=Number(d||0);d<e;d++)this[d]=a;return this}},"es6-impl","es3");
var c=document.getElementById("umCanvas"),ctx=c.getContext("2d");Intersecction=function(a,b){this.overlap=a;this.contains=b};MTV=function(a,b,d){this.axis=a;this.magnitude=b;this.contains=d};Versor=function(a,b){this.x=a;this.y=b};Point=function(a,b){this.x=a;this.y=b};Vector=function(a,b){this.x=a;this.y=b};Projection=function(a,b){this.min=a;this.max=b};function distance(a,b){var d=a.x-b.x,e=a.y-b.y;return Math.sqrt(d*d+e*e)}function calculateVector(a,b,d){d.x=a.x-b.x;d.y=a.y-b.y}
function norm(a){return Math.sqrt(a.x*a.x+a.y*a.y)}function radiansToDegrees(a){return 180*a/Math.PI}function degreesToRadians(a){return a*Math.PI/180}function angleVectors(a,b){unitA=new Vector(0,0);unitB=new Vector(0,0);unitVector(a,unitA);unitVector(b,unitB);var d=dotProduct(unitA,unitB);return Math.acos(d)}function normalVector1(a,b,d){x=a.x-b.x;y=a.y-b.y;d.x=-y;d.y=x}function normalVector2(a,b,d){x=a.x-b.x;y=a.y-b.y;d.x=y;d.y=-x}
function unitVector(a,b){var d=norm(a);0!=d?(b.x=a.x/d,b.y=a.y/d):(b.x=0,b.y=0)}function dotProduct(a,b){return a.x*b.x+a.y*b.y}function projection(a,b){min=99999;max=-99999;for(var d,e=0;e<a.length;e++)d=dotProduct(a[e],b),d>max&&(max=d),d<min&&(min=d);return new Projection(min,max)}function projectionCircle(a,b){var d;d=dotProduct(a.position,b);min=d-a.radius;max=d+a.radius;return new Projection(min,max)}
function collisionCircles(a,b){var d=distance(a.position,b.position),e=d-(a.radius+b.radius),g=!1;if(0>e){var f=a.radius;b.radius>f&&(f=b.radius);f>d&&(g=!0);a.findAxis(b.position);unitVector(a.axis,a.axis);return new MTV(new Vector(a.axis.x,a.axis.y),-e,g)}return!1}
function circleSTA(a,b){dist=1E4;closest=-1;for(var d=0;d<b.vertices.length;d++)aux=distance(a.position,b.vertices[d]),aux<dist&&(dist=aux,closest=d);a.findAxis(b.vertices[closest]);unitVector(a.axis,a.axis);var e=projectionCircle(a,a.axis),g=projection(b.vertices,a.axis),f=999999,h=!1;intersect=overlap(e,g);if(0==intersect.overlap)return!1;intersect.overlap<f&&(f=intersect.overlap,smallestAxis=a.axis,h=intersect.contains);for(d=0;d<b.axes.length;d++){e=projectionCircle(a,b.axes[d]);g=projection(b.vertices,
b.axes[d]);intersect=overlap(e,g);if(0==intersect.overlap)return!1;intersect.overlap<f&&(f=intersect.overlap,smallestAxis=b.axes[d],h=intersect.contains)}distance(a.position,b.center)<a.radius&&(h=!0);b.hit=!0;a.hit=!0;return new MTV(new Vector(a.axis.x,a.axis.y),f,h)}
function collisionSTA(a,b){if(1==a.sides&&1==b.sides)return collisionCircles(a,b);if(1==a.sides)return circleSTA(a,b);if(1==b.sides)return circleSTA(b,a);for(var d=999999,e=null,g=!1,f=0;f<a.axes.length;f++){projA=projection(a.vertices,a.axes[f]);projB=projection(b.vertices,a.axes[f]);intersect=overlap(projA,projB);if(0==intersect.overlap)return!1;intersect.overlap<d&&(d=intersect.overlap,e=a.axes[f],g=intersect.contains)}for(f=0;f<b.axes.length;f++){projA=projection(a.vertices,b.axes[f]);projB=projection(b.vertices,
b.axes[f]);intersect=overlap(projA,projB);if(0==intersect.overlap)return!1;intersect.overlap<d&&(d=intersect.overlap,e=b.axes[f],g=intersect.contains)}a.hit=!0;b.hit=!0;return new MTV(new Vector(e.x,e.y),d,g)}
function debugSTA(a,b){if(1==a.sides&&1==b.sides)return collisionCircles(a,b);if(1==a.sides)return circleSTA(a,b);if(1==b.sides)return circleSTA(b,a);var d=999999,e=null,g=!1;colorA="#FF0000";colorB="#0000FF";overlaps=[];var f;new Intersecction;for(var h=0;h<a.axes.length;h++){projA=projection(a.vertices,a.axes[h]);projB=projection(b.vertices,a.axes[h]);drawProjection(projA,a.axes[h],colorA);drawProjection(projB,a.axes[h],colorB);f=overlap(projA,projB);overlaps.push(f.overlap);if(0==f.overlap)return console.log(overlaps),
!1;f.overlap<d&&(d=f.overlap,e=a.axes[h],g=f.contains)}for(h=0;h<b.axes.length;h++){projA=projection(a.vertices,b.axes[h]);projB=projection(b.vertices,b.axes[h]);drawProjection(projA,b.axes[h],colorA);drawProjection(projB,b.axes[h],colorB);f=overlap(projA,projB);overlaps.push(f.overlap);if(0==f.overlap)return console.log(overlaps),!1;f.overlap<d&&(d=f.overlap,e=b.axes[h],g=f.contains)}console.log(overlaps);a.hit=!0;b.hit=!0;return new MTV(new Vector(e.x,e.y),d,g)}
function overlap(a,b){var d=new Intersecction(0,!1);if(b.min<a.max&&b.max>a.max)d.overlap=b.min-a.max;else if(b.max>a.min&&b.min<a.min)d.overlap=a.min-b.max;else if(b.min>a.min&&b.max<a.max){d.overlap=a.max-b.max;var e=Math.abs(a.min-b.min),g=Math.abs(a.max-b.max);d.overlap=e<g?d.overlap+e:d.overlap+g;d.contains=!0}return d}
function rotatePolygon(a,b){b=degreesToRadians(b);if(1!=a.sides)for(i=0;i<a.vertices.length;i++)a.vertices[i].x-=a.center.x,a.vertices[i].y-=a.center.y,x=a.vertices[i].x*Math.cos(b)-a.vertices[i].y*Math.sin(b),y=a.vertices[i].x*Math.sin(b)+a.vertices[i].y*Math.cos(b),a.vertices[i].x=x+a.center.x,a.vertices[i].y=y+a.center.y}var angle=1*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle);
function simpleRotate(a){for(i=0;i<a.vertices.length;i++)a.vertices[i].x-=a.center.x,a.vertices[i].y-=a.center.y,x=a.vertices[i].x*cos-a.vertices[i].y*sin,y=a.vertices[i].x*sin+a.vertices[i].y*cos,a.vertices[i].x=x+a.center.x,a.vertices[i].y=y+a.center.y}function listToVertices(a){vertices=[];0!=a.length%2&&console.log("Error: list is not a valid set of coordinates.");for(var b=0;b<a.length;b+=2)this.vertices[b/2]=new Point(a[b],a[b+1]);return vertices}function times2(a){return 2*a}
function drawProjection(a,b,d){d=void 0===d?"#000000":d;ctx.save();ctx.beginPath();0>b.x&&0>b.y?ctx.translate(c.width,c.height):0>b.x?ctx.translate(c.width,0):0>b.y&&ctx.translate(0,c.height);ctx.lineWidth=12;ctx.strokeStyle=d;d=new Point(a.min*b.x,a.min*b.y);a=new Point(a.max*b.x,a.max*b.y);ctx.moveTo(d.x,d.y);ctx.lineTo(a.x,a.y);ctx.stroke();ctx.restore()}
function drawCircle(a,b,d,e,g){b=void 0===b?"#0000FF":b;d=void 0===d?"#FF0000":d;e=void 0===e?!1:e;g=void 0===g?"#00F0FF":g;ctx.save();ctx.beginPath();ctx.strokeStyle=1==a.hit?d:b;ctx.arc(a.position.x,a.position.y,a.radius,0,2*Math.PI);ctx.stroke();e&&(ctx.fillStyle=g,ctx.beginPath(),ctx.arc(a.position.x,a.position.y,3,0,2*Math.PI),ctx.fill());ctx.restore()}
function drawPolygon(a,b,d,e,g,f,h){b=void 0===b?"#0000FF":b;d=void 0===d?"#FF0000":d;e=void 0===e?!0:e;g=void 0===g?!0:g;f=void 0===f?"#00F0FF":f;h=void 0===h?"#0000FF":h;ctx.save();ctx.beginPath();ctx.strokeStyle=1==a.hit?d:b;ctx.moveTo(a.vertices[0].x,a.vertices[0].y);for(b=0;b<a.vertices.length;b++)ctx.lineTo(a.vertices[b].x,a.vertices[b].y);ctx.lineTo(a.vertices[0].x,a.vertices[0].y);ctx.stroke();ctx.fillStyle=h;if(e)for(b=0;b<a.vertices.length;b++)ctx.beginPath(),ctx.arc(a.vertices[b].x,a.vertices[b].y,
3,0,2*Math.PI),ctx.fill();g&&void 0!=a.center&&(ctx.fillStyle=f,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,3,0,2*Math.PI),ctx.fill());ctx.restore()}midPoint=function(a,b){vector=new Vector(0,0);calculateVector(a,b,vector);vector.x*=.5;vector.y*=.5;this.x=a.x-vector.x;this.y=a.y-vector.y};function drawVector(a,b){ctx.beginPath();ctx.strokeStyle="#00FF00";ctx.moveTo(a.x,a.y);ctx.lineTo(a.x+b.x,a.y+b.y);ctx.stroke()}
function calculateAxes(a){if(1!=a.sides){if(4==a.sides){for(var b=0;b<a.vertices.length-1;b++)normalVector1(a.vertices[b],a.vertices[b+1],a.axes[b]),unitVector(a.axes[b],a.axes[b]);normalVector1(a.vertices[b],a.vertices[0],a.axes[b])}else{for(b=0;b<a.vertices.length-1;b++)normalVector2(a.vertices[b],a.vertices[b+1],a.axes[b]),unitVector(a.axes[b],a.axes[b]);normalVector2(a.vertices[b],a.vertices[0],a.axes[b])}unitVector(a.axes[b],a.axes[b])}}
function drawAxes(a,b){var d=new Vector(0,0);if(1!=a.sides){for(var e=0;e<a.vertices.length-1;e++){var g=new midPoint(a.vertices[e],a.vertices[e+1]);d.x=a.axes[e].x*b;d.y=a.axes[e].y*b;drawVector(g,d)}g=new midPoint(a.vertices[e],a.vertices[0]);d.x=a.axes[e].x*b;d.y=a.axes[e].y*b;drawVector(g,d)}}function drawFPS(a,b){b=void 0===b?"#000FFF":b;ctx.beginPath();ctx.fillStyle=b;ctx.font="14px Arial";string="FPS: "+a;ctx.fillText(string,10,20);ctx.stroke()}
var Rect=function(a,b,d,e,g,f,h,k){var l=[];l.push(a);l.push(b);l.push(a+d);l.push(b);l.push(a+d);l.push(b+e);l.push(a);l.push(b+e);this.vertices=listToVertices(l);this.position=new Point(a,b);this.width=d;this.height=e;this.mass=d*e;this.center=new Point(a+d/2,b+e/2);this.hit=!1;this.versor=new Versor(g,f);this.velocity=h;this.spin=k;this.sides=4;this.axes=[];this.projections=[];for(a=0;a<this.sides;a++)this.axes[a]=new Vector(0,0),this.projections[a]=new Projection(0,0);this.applyVector=function(a){for(var b=
0;b<this.vertices.length;b++)this.vertices[b].x+=a.x,this.vertices[b].y+=a.y;this.position.x+=a.x;this.position.y+=a.y;this.center.x=this.position.x+.5*this.width;this.center.y=this.position.y+.5*this.height};this.update=function(){xIncrement=this.versor.x*this.velocity;yIncrement=this.versor.y*this.velocity;incrementVertices(this.vertices,xIncrement,yIncrement);incrementRect(this,xIncrement,yIncrement);this.hit=!1};this.moveTo=function(a){var b=new Vector(0,0);calculateVector(a,this.center,b);this.applyVector(b)}},
Triangle=function(a,b,d,e,g,f,h){var k=[];k.push(a);k.push(b);k.push(a+d);k.push(b);k.push(a+.5*d);k.push(b-d);this.vertices=listToVertices(k);this.position=new Point(a,b);this.side=d;this.mass=d*d*.5;this.center=new Point(a+d/2,b-d/3);this.hit=!1;this.versor=new Versor(e,g);this.velocity=f;this.spin=h;this.sides=3;this.axes=[];this.projections=[];for(a=0;a<this.sides;a++)this.axes[a]=new Vector(0,0),this.projections[a]=new Projection(0,0);this.applyVector=function(a){for(var b=0;b<this.vertices.length;b++)this.vertices[b].x+=
a.x,this.vertices[b].y+=a.y};this.update=function(){xIncrement=this.versor.x*this.velocity;yIncrement=this.versor.y*this.velocity;incrementVertices(this.vertices,xIncrement,yIncrement);for(var a=0,b=0,d=0;d<this.vertices.length;d++)a+=this.vertices[d].x,b+=this.vertices[d].y;this.center.x=a/3;this.center.y=b/3;this.hit=!1};this.moveTo=function(a){var b=new Vector(0,0);calculateVector(a,this.center,b);this.applyVector(b)}};
function applyVectorToRect(a,b){for(var d=0;d<a.vertices.length;d++)a.vertices[d].x+=b.x,a.vertices[d].y+=b.y;a.position.x+=b.x;a.position.y+=b.y;a.center.x=a.position.x+.5*a.width;a.center.y=a.position.y+.5*a.height}function incrementVertices(a,b,d){for(var e=0;e<a.length;e++)a[e].x+=b,a[e].y+=d}function incrementRect(a,b,d){a.position.x+=b;a.position.y+=d;a.center.x=a.position.x+.5*a.width;a.center.y=a.position.y+.5*a.height}
var Circle=function(a,b,d,e,g,f,h){var k=[];k.push(a);k.push(b);this.position=new Point(a,b);this.radius=d;this.mass=d*d;this.hit=!1;this.versor=new Versor(e,g);this.velocity=f;this.spin=h;this.sides=1;this.axis=new Vector(0,0);this.projections=[];this.applyVector=function(a){this.position.x+=a.x;this.position.y+=a.y};this.update=function(){xIncrement=this.versor.x*this.velocity;yIncrement=this.versor.y*this.velocity;this.position.x+=xIncrement;this.position.y+=yIncrement;this.hit=!1};this.findAxis=
function(a){calculateVector(this.position,a,this.axis)};this.moveTo=function(a){var b=new Vector(0,0);calculateVector(a,this.position,b);this.applyVector(b)}};
function checkBorderCircle(a,b){rightBound=a.position.x+a.radius;leftBound=a.position.x-a.radius;lowerBound=a.position.y+a.radius;upperBound=a.position.y-a.radius;var d=!1;rightBound>c.width?(diff=new Vector(-(rightBound-c.width),0),a.applyVector(diff),a.versor.x*=-1,void 0!=b&&b(axis="x"),d=!0):0>leftBound?(diff=new Vector(-leftBound,0),a.applyVector(diff),a.versor.x*=-1,void 0!=b&&b(axis="x"),d=!0):lowerBound>c.height?(diff=new Vector(0,-(lowerBound-c.height)),a.applyVector(diff),a.versor.y*=-1,
void 0!=b&&b(axis="y"),d=!0):0>upperBound&&(diff=new Vector(0,-upperBound),a.applyVector(diff),a.versor.y*=-1,void 0!=b&&b(axis="y"),d=!0);return d}
function checkBorder(a,b){if(1==a.sides)checkBorderCircle(a,b);else return yAxis=new Vector(0,1),xAxis=new Vector(1,0),projX=projection(a.vertices,xAxis),projY=projection(a.vertices,yAxis),hit=!1,projX.max>c.width?(a.versor.x*=-1,diff=new Vector(-(projX.max-c.width),0),a.applyVector(diff),void 0!=b&&b(axis="x"),hit=!0):0>projX.min&&(a.versor.x*=-1,diff=new Vector(-projX.min,0),a.applyVector(diff),void 0!=b&&b(axis="x"),hit=!0),projY.max>c.height&&(a.versor.y*=-1,diff=new Vector(0,-(projY.max-c.height)),
a.applyVector(diff),void 0!=b&&b(axis="y"),hit=!0),0>projY.min&&(a.versor.y*=-1,diff=new Vector(0,-projY.min),a.applyVector(diff),void 0!=b&&b(axis="y"),hit=!0),hit}function changeDirection(a,b){a.versor.x=b.x;a.versor.y=b.y}
function smartCollision(a,b,d){var e=collisionSTA(a,b);if(0==e)return!1;var g=a.mass-b.mass,g=Math.abs(g);smaller=Math.min(a.mass,b.mass);g<smaller&&elasticCollision(a,b,void 0,void 0,.1);g<4*smaller?partiallyElasticCollision(a,e,b):unilateralElasticCollision(a,e,b);void 0!=d&&d()}function unilateralElasticCollision(a,b,d){a.mass>d.mass?(b.axis.x=-b.axis.x,b.axis.y=-b.axis.y,changeDirection(d,b.axis)):changeDirection(a,b.axis)}
function elasticCollision(a,b,d,e,g){var f=collisionSTA(a,b);if(0==f)return!1;var h=new Vector(0,0);f.contains?(h.x=f.axis.x*f.magnitude,h.y=f.axis.y*f.magnitude):(h.x=f.axis.x*f.magnitude*g,h.y=f.axis.y*f.magnitude*g);b.applyVector(h);if(void 0!=e)for(g=0;g<e.length;g++)e[g].applyVector(h);h.x*=-1;h.y*=-1;a.applyVector(h);if(void 0!=d)for(g=0;g<d.length;g++)d[g].applyVector(h);changeDirection(a,f.axis);f.axis.x=-f.axis.x;f.axis.y=-f.axis.y;changeDirection(b,f.axis);return!0}
function getInertiaNorm(a){return a.mass*a.velocity}
function inelasticCollision(a,b){inertiaA=new Vector(0,0);inertiaB=new Vector(0,0);result=new Vector(0,0);partialA=getInertiaNorm(a);inertiaA.x=partialA*a.versor.x;inertiaA.y=partialA*a.versor.y;partialB=getInertiaNorm(b);inertiaB.x=partialB*b.versor.x;inertiaB.y=partialB*b.versor.y;result.x=inertiaA.x+inertiaB.x;result.y=inertiaA.y+inertiaA.y;unitVector(result,result);a.versor=result;b.versor=result;a.spin=0;b.spin=0;2<a.velocity&&--a.velocity;2<b.velocity&&--b.velocity}
function partiallyElasticCollision(a,b,d){b=collisionSTA(a,d);0!=b&&(new Vector(0,0),d.mass>a.mass?(bigger=d,smaller=a,sign=-1,changeDirection(a,b.axis)):(bigger=a,smaller=d,sign=1,b.axis.x=-b.axis.x,b.axis.y=-b.axis.y,changeDirection(d,b.axis)),inertiaBig=new Vector(0,0),inertiaSmaller=new Vector(0,0),result=new Vector(0,0),partialBig=getInertiaNorm(bigger),inertiaBig.x=partialBig*a.versor.x,inertiaBig.y=partialBig*a.versor.y,partialSmaller=getInertiaNorm(smaller),inertiaSmaller.x=partialSmaller*
d.versor.x,inertiaSmaller.y=partialSmaller*d.versor.y,result.x=inertiaBig.x+inertiaSmaller.x,result.y=inertiaBig.y+inertiaSmaller.y,bigger.x=result.x,bigger.y=result.y)}function checkElasticCollisionsNaive(a,b){var d,e;for(d=0;d<a.length;d++)for(e=d+1;e<a.length;e++)elasticCollision(a[e],a[d],void 0,void 0,b)}function checkColisionsNaive(a){var b,d;for(b=0;b<a.length;b++)for(d=b+1;d<a.length;d++)smartCollision(a[d],a[b])}function smallest(a,b){return a<=b?a:b}
Fps=function(){this.index=0;this.array=[];this.maxSize=24;this.add=function(a){this.array[this.index]=1E3/a;this.index=(this.index+1)%this.maxSize};this.mean=0;this.calculateMean=function(){for(var a=0,b=0;b<this.array.length;b++)a+=this.array[b];this.mean=Math.round(a/this.array.length)}};
function randomRect(a,b,d,e){var g=Math.ceil(Math.random()*c.width/2)+a,f=Math.ceil(Math.random()*c.height/2)+a,h=Math.ceil(Math.random()*a)+b;a=Math.ceil(Math.random()*a)+b;b=Math.round(Math.random()+1);b=Math.pow(-1,b);return rect=new Rect(g,f,h,a,Math.random(),Math.random(),d,Math.ceil(Math.random()*e*b))}
function randomTriangle(a,b,d,e){var g=Math.ceil(Math.random()*c.width/2)+a,f=Math.ceil(Math.random()*c.height/2)+a;a=Math.ceil(Math.random()*a)+b;b=Math.round(Math.random()+1);b=Math.pow(-1,b);return triangle=new Triangle(g,f,a,Math.random(),Math.random(),d,Math.ceil(Math.random()*e*b))}
function randomCircle(a,b,d,e){var g=Math.ceil(Math.random()*c.width/2)+a,f=Math.ceil(Math.random()*c.height/2)+a;a=Math.ceil(Math.random()*a)+b;b=Math.round(Math.random()+1);b=Math.pow(-1,b);return circle=new Circle(g,f,a,Math.random(),Math.random(),d,Math.ceil(Math.random()*e*b))};
var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,e){if(e.get||e.set)throw new TypeError("ES3 does not support getters and setters.");b!=Array.prototype&&b!=Object.prototype&&(b[d]=e.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,d,e,f){if(d){e=$jscomp.global;b=b.split(".");for(f=0;f<b.length-1;f++){var g=b[f];g in e||(e[g]={});e=e[g]}b=b[b.length-1];f=e[b];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.fill",function(b){return b?b:function(d,e,b){var f=this.length||0;0>e&&(e=Math.max(0,f+e));if(null==b||b>f)b=f;b=Number(b);0>b&&(b=Math.max(0,f+b));for(e=Number(e||0);e<b;e++)this[e]=d;return this}},"es6-impl","es3");
var Phases=function(){this.phase6=this.phase5=this.phase4=this.phase3=this.phase2=this.phase1=!1;this.current=0},EnergySource=function(b,d,e){e=void 0===e?500:e;this.current=this.max=void 0===b?100:b;this.rechargeRate=void 0===d?10:d;this.rechargeSpeed=e;this.rechargeEvent=void 0;this.recharging=!0;this.getValue=function(){var b=this.max*this.rechargeRate,b=b/1E3*(1E3-e);return b=Math.round(b)};this.describe=function(){var b=[];b.push("Max points: "+this.max,"Recharge Rate: "+this.rechargeRate,"Recharge Speed: "+
this.rechargeSpeed/1E3+" seconds");return b};this.recharge=function(b){this.recharging&&(this.current<this.max&&(this.current+=this.rechargeRate,this.current>this.max&&(this.current=this.max),this.recharging=!1,this.rechargeEvent=void 0),void 0==this.rechargeEvent&&(this.rechargeEvent=setTimeout(function(){b.recharging=!0},b.rechargeSpeed)))};this.drain=function(b){this.current-=b;0>this.current&&(this.current=0)}},Shield=function(b,d,e,f,g){this.enabled=!1;this.max=void 0===b?100:b;this.current=
0;this.drainRate=void 0===e?10:e;this.rechargeEfficiency=void 0===f?.5:f;this.drainSpeed=void 0===g?250:g;this.draining=!0;this.drainEvent=void 0;this.powerSupply=new EnergySource(0,0);this.resistance=0;this.resistanceType="f";this.getValue=function(){value=this.max*(this.resistance+1);value*=this.rechargeEfficiency;value*=1E3-this.drainSpeed;return value=Math.round(value/100)};this.describe=function(){var a=[];a.push("Max points: "+this.max,"Drain Rate: "+this.drainRate,"Recharge Efficiency: "+this.rechargeEfficiency,
"Drain Speed: "+this.drainSpeed/1E3+" seconds","Resistance: "+this.resistance);return a};this.setPowerSupply=function(a){this.powerSupply=a};this.setEnabled=function(a){this.enabled=a};this.drainEnergy=function(a){this.draining&&this.enabled&&(this.draining=!1,this.drainingEvent=void 0,void 0===this.drainingEvent&&(this.drainingEvent=setTimeout(function(){a.draining=!0},a.drainSpeed)),this.current<this.max&&(this.powerSupply.current>this.drainRate?(this.current+=this.drainRate*this.rechargeEfficiency,
this.powerSupply.current-=this.drainRate):(this.current+=this.powerSupply.current*this.rechargeEfficiency,this.powerSupply.current=0),this.current>this.max&&(this.current=this.max)))};this.sufferDamage=function(a){a="f"==this.resistanceType?a-this.resistance:a*this.resistance;0<a&&(this.current-=a);0>this.current?(a=-1*this.current,this.current=0):a=0;return a}},Hull=function(b,d){d=void 0===d?0:d;this.current=this.max=void 0===b?100:b;this.resistance=d;this.resistanceType="f";this.getValue=function(){return value=
this.max*(this.resistance+1)};this.describe=function(){var b=[];b.push("Max points: "+this.max,"Resistance: "+this.resistance);return b};this.sufferDamage=function(b){b="f"==this.resistanceType?b-d:b*d;0<b&&(this.current-=b)};this.recover=function(b){this.current+=b;this.current>this.max&&(this.current=this.max)}},Ship=function(b,d,e,f,g){f=void 0===f?"#0000FF":f;g=void 0===g?"#00F0FF":g;this.hitbox=new Triangle(b,d,e,0,0,0,0);this.primaryColor=f;this.secondaryColor=g;this.auxHitbox=new Triangle(b,
d-e,e,0,0,0,0);this.powerSupply=new EnergySource(100,10);this.hull=new Hull;this.shield=new Shield;this.dead=this.immunity=!1;this.weapons=[];this.currentWeapon=0;this.isStrafing=this.isTurning=this.braking=this.reverseEngine=this.engineOn=this.lock=!1;this.strafingSide=0;this.acceleration=.125;this.maxSpeed=4;this.turnRate=3.5;this.turning=!1;this.rotate=0;this.front=new Point(this.hitbox.vertices[2].x,this.hitbox.vertices[2].y);this.inertiaVector=new Vector(0,0);this.engineVersor=new Vector(0,0);
this.engineVector=new Vector(0,0);this.strafingVector=new Vector(0,0);this.autoPath=new Point(0,0);this.getEngineValue=function(){var a=10*this.maxSpeed,a=a+1E3*this.acceleration,a=a+100*this.turnRate;return Math.round(a)};this.describeEngine=function(){var a=[];a.push("Max Speed: "+this.maxSpeed,"Acceleration : "+this.acceleration,"Turn Rate: "+this.turnRate);return a};this.getValue=function(){for(var a=this.getEngineValue(),a=a+this.hull.getValue(),a=a+this.shield.getValue(),a=a+this.powerSupply.getValue(),
b=0;b<this.weapons.length;b++)a+=this.weapons[b].getValue();return a};this.updateDirection=function(){if(this.engineOn||this.reverseEngineOn||0!=this.braking){this.inertiaVector.x=this.hitbox.versor.x*this.hitbox.velocity;this.inertiaVector.y=this.hitbox.versor.y*this.hitbox.velocity;this.engineOn?(calculateVector(this.front,this.hitbox.center,this.engineVersor),unitVector(this.engineVersor,this.engineVersor),this.engineVector.x=this.engineVersor.x*this.acceleration,this.engineVector.y=this.engineVersor.y*
this.acceleration):this.braking?(unitVector(this.inertiaVector,this.engineVersor),this.engineVersor.x*=-1,this.engineVersor.y*=-1,this.acceleration>this.hitbox.velocity?(this.engineVector.x=this.engineVersor.x*this.hitbox.velocity,this.engineVector.y=this.engineVersor.y*this.hitbox.velocity):(this.engineVector.x=this.engineVersor.x*this.acceleration,this.engineVector.y=this.engineVersor.y*this.acceleration)):(calculateVector(this.front,this.hitbox.center,this.engineVersor),unitVector(this.engineVersor,
this.engineVersor),this.reverseEngineOn&&(this.engineVersor.x*=-1,this.engineVersor.y*=-1,this.engineVector.x=this.engineVersor.x*this.acceleration,this.engineVector.y=this.engineVersor.y*this.acceleration));var a=new Vector(this.engineVector.x+this.inertiaVector.x,this.engineVector.y+this.inertiaVector.y),b=norm(a);b<=this.maxSpeed?0==b?(this.hitbox.velocity=b,this.hitbox.versor.x=0,this.hitbox.versor.y=0):(unitVector(a,a),this.hitbox.velocity=b,this.hitbox.versor.x=a.x,this.hitbox.versor.y=a.y):
(unitVector(a,a),this.hitbox.versor.x=a.x,this.hitbox.versor.y=a.y);this.auxHitbox.velocity=this.hitbox.velocity;this.auxHitbox.versor=this.hitbox.versor}};this.updatePosition=function(){this.hitbox.update();this.auxHitbox.update();this.front.x=this.hitbox.vertices[2].x;this.front.y=this.hitbox.vertices[2].y};this.updateTurn=function(){if(this.isTurning){this.hitbox.spin=0;this.auxHitbox.spin=0;rotatePolygon(this.hitbox,this.rotate);theta=degreesToRadians(this.rotate);for(var a=0;a<this.auxHitbox.vertices.length;a++)this.auxHitbox.vertices[a].x-=
this.hitbox.center.x,this.auxHitbox.vertices[a].y-=this.hitbox.center.y,b=this.auxHitbox.vertices[a].x*Math.cos(theta)-this.auxHitbox.vertices[a].y*Math.sin(theta),d=this.auxHitbox.vertices[a].x*Math.sin(theta)+this.auxHitbox.vertices[a].y*Math.cos(theta),this.auxHitbox.vertices[a].x=b+this.hitbox.center.x,this.auxHitbox.vertices[a].y=d+this.hitbox.center.y}};this.turn=function(a,b){this.isTurning=b;this.rotate="l"==a?-this.turnRate:this.turnRate};this.updateStrafe=function(){if(this.isStrafing){this.inertiaVector.x=
this.hitbox.versor.x*this.hitbox.velocity;this.inertiaVector.y=this.hitbox.versor.y*this.hitbox.velocity;var a=new midPoint(this.hitbox.vertices[0],this.hitbox.vertices[1]);-1==this.strafingSide?calculateVector(a,this.hitbox.vertices[0],this.strafingVector):calculateVector(a,this.hitbox.vertices[1],this.strafingVector);unitVector(this.strafingVector,this.strafingVector);this.strafingVector.x=this.strafingVector.x*this.acceleration/3;this.strafingVector.y=this.strafingVector.y*this.acceleration/3;
var a=new Vector(this.strafingVector.x+this.inertiaVector.x,this.strafingVector.y+this.inertiaVector.y),b=norm(a);b<=this.maxSpeed?0==b?(this.hitbox.velocity=b,this.hitbox.versor.x=0,this.hitbox.versor.y=0):(unitVector(a,a),this.hitbox.velocity=b,this.hitbox.versor.x=a.x,this.hitbox.versor.y=a.y):(unitVector(a,a),this.hitbox.versor.x=a.x,this.hitbox.versor.y=a.y);this.auxHitbox.velocity=this.hitbox.velocity;this.auxHitbox.versor=this.hitbox.versor}};this.strafe=function(a,b){this.isStrafing=b;this.strafingSide=
"l"==a?1:-1};this.throttle=function(a){this.engineOn=a};this.brake=function(a){this.braking=a};this.reverseThrottle=function(a){this.reverseEngineOn=a};this.calculateAngle=function(a){pathVector=new Vector(0,0);frontVector=new Vector(0,0);calculateVector(a,this.hitbox.center,pathVector);0==this.hitbox.velocity?(calculateVector(this.front,this.hitbox.center,frontVector),unitVector(frontVector,frontVector)):(frontVector.x=this.engineVersor.x,frontVector.y=this.engineVersor.y);translatedPoint=new Point(this.hitbox.center.x-
a.x,this.hitbox.center.y-a.y);list=[];list.push(translatedPoint);rotatedVector=new Vector(0,0);a=degreesToRadians(90);rotatedVector.x=frontVector.x*Math.cos(a)-frontVector.y*Math.sin(a);rotatedVector.y=frontVector.x*Math.sin(a)+frontVector.y*Math.cos(a);myProjection=projection(list,rotatedVector);this.pathAngle=angleVectors(frontVector,pathVector);this.pathAngle=radiansToDegrees(this.pathAngle);0<myProjection.min&&(this.pathAngle*=-1)};this.drawAutoPath=function(){this.lock&&(ctx.setLineDash([4]),
ctx.strokeStyle=this.primaryColor,ctx.beginPath(),ctx.moveTo(this.hitbox.center.x,this.hitbox.center.y),ctx.lineTo(this.autoPath.x,this.autoPath.y),ctx.stroke(),ctx.setLineDash([0]))};this.autoRotate=function(){0!=this.pathAngle&&(0<this.pathAngle?this.pathAngle>=this.turnRate?(this.pathAngle-=this.turnRate,this.turn("r",!0)):(this.turn("r",!0),this.updateTurn(),this.turn("l",!1),this.pathAngle=0):this.pathAngle<this.turnRate?(this.pathAngle+=this.turnRate,this.turn("l",!0)):(this.turn("l",!0),this.updateTurn(),
this.turn("l",!1),this.pathAngle=0))};this.autoPilot=function(){this.lock&&(this.autoStatus.phase1?(this.calculateAngle(this.autoPath),this.autoStatus.phase1=!1,this.autoStatus.current++):this.autoStatus.phase2?(this.throttle(!1),this.brake(!0),0==this.hitbox.velocity&&(this.autoStatus.phase2=!1,this.brake(!1),this.autoStatus.current++)):this.autoStatus.phase3?(this.calculateAngle(this.autoPath),this.autoStatus.phase3=!1):this.autoStatus.phase4?(this.autoRotate(),0==this.pathAngle&&(this.autoStatus.phase4=
!1)):this.autoStatus.phase5?distance(this.hitbox.center,this.autoPath)/this.hitbox.velocity>this.hitbox.velocity/this.acceleration?this.throttle(!0):(this.autoStatus.phase5=!1,this.throttle(!1)):this.autoStatus.phase6&&(this.brake(!0),0==this.hitbox.velocity&&(this.autoStatus.phase6=!1,this.brake(!1),this.lock=!1)))};this.autoStatus=new Phases;this.setupAutoPilot=function(a){this.autoPath=new Point(a.x,a.y);this.autoStatus.phase1=!0;this.autoStatus.phase2=!0;this.autoStatus.phase3=!0;this.autoStatus.phase4=
!0;this.autoStatus.phase5=!0;this.autoStatus.phase6=!0;this.autoStatus.current=0};this.drawStatus=function(a){a=void 0===a?this.secondaryColor:a;canvas=void 0==camera?c:camera;ctx.beginPath();ctx.font="14px Arial";ctx.fillStyle=a;string="Hull: "+this.hull.current;ctx.fillText(string,canvas.width-200,30);string="Immunity: "+this.immunity;ctx.fillText(string,canvas.width-200,60);string="Energy: "+this.powerSupply.current;ctx.fillText(string,canvas.width-200,90);void 0!=this.shield&&(string=this.shield.enabled?
"Shield enabled: "+this.shield.current:"Shield disabled: "+this.shield.current,ctx.fillText(string,canvas.width-200,120))};this.draw=function(a){a=void 0===a?this.hitbox:a;ctx.save();ctx.lineWidth=3;ctx.beginPath();1==a.hit&&0==this.shield.current?(ctx.strokeStyle="#FF0000",ctx.fillStyle="#FF0000"):(ctx.strokeStyle=this.primaryColor,ctx.fillStyle=this.primaryColor);for(var b=0;b<a.vertices.length;b++)ctx.beginPath(),ctx.arc(a.vertices[b].x,a.vertices[b].y,3,0,2*Math.PI),2==b&&(ctx.fillStyle=this.secondaryColor),
ctx.fill();for(b=0;b<a.vertices.length-1;b++)ctx.beginPath(),ctx.moveTo(a.center.x,a.center.y),ctx.lineTo(a.vertices[b].x,a.vertices[b].y),ctx.stroke();for(b=0;b<a.vertices.length-1;b++)ctx.beginPath(),ctx.moveTo(a.vertices[2].x,a.vertices[2].y),ctx.lineTo(a.vertices[b].x,a.vertices[b].y),ctx.stroke();void 0!=a.center&&(ctx.fillStyle=this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,3,0,2*Math.PI),ctx.fill());1==this.immunity&&(ctx.strokeStyle=this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,
a.center.y,a.side+2,0,2*Math.PI),ctx.stroke());this.shield.enabled&&0<this.shield.current&&(ctx.save(),ctx.strokeStyle=1==a.hit?this.primaryColor:this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,a.side+2,0,2*Math.PI),ctx.stroke(),ctx.restore());ctx.restore()};this.setImmunity=function(a){this.immunity=!0;setTimeout(function(){this.player.immunity=!1},1E3*a)};this.addWeapon=function(a){this.weapons.push(a)};this.changeWeapon=function(){this.weapons[this.currentWeapon].firing=!1;this.currentWeapon++;
this.currentWeapon%=this.weapons.length;this.weapon=this.weapons[this.currentWeapon]};this.cycleEnabledWeapons=function(){this.currentWeapon++;this.currentWeapon%=this.weapons.length;this.weapons[this.currentWeapon].enabled=this.weapons[this.currentWeapon].enabled?!1:!0};this.sufferDamage=function(a){1!=this.immunity&&(void 0!=this.shield&&this.shield.enabled&&0<this.shield.current?(a=this.shield.sufferDamage(a))&&this.hull.sufferDamage(a):this.hull.sufferDamage(a),0>this.hull.current&&(this.dead=
!0))}};function displayValueConsole(b){console.log("engine: "+b.getEngineValue());console.log("hull:"+b.hull.getValue());console.log("shield:"+b.shield.getValue());console.log("power source:"+b.powerSupply.getValue());console.log("Weapons");for(var d=0;d<b.weapons.length;d++)console.log(b.weapons[d].name+": "+b.weapons[d].getValue());console.log("ship total: "+b.getValue())}
function describeShipConsole(b){console.log(b.name);var d;d="Shield --"+JSON.stringify(b.shield.describe());console.log(d);d="Hull--"+JSON.stringify(b.hull.describe());console.log(d);d="Energy Source--"+JSON.stringify(b.powerSupply.describe());console.log(d);d="Engine--"+JSON.stringify(b.describeEngine());console.log(d)}
function drawStats(b){ctx.save();ctx.beginPath();ctx.fillStyle="#FFFFFF";ctx.fillRect(c.width/3-20,20,c.width/1.5,20*(6+b.weapons.length));ctx.fillStyle="#000000";ctx.font="11px arial";for(var d="Hull--"+JSON.stringify(b.hull.describe()),e=0;10>e;e++)d=d.replace('"',"");ctx.fillText(d,c.width/3,40);d="Engine--"+JSON.stringify(b.describeEngine());for(e=0;10>e;e++)d=d.replace('"',"");ctx.fillText(d,c.width/3,60);d="Energy Source--"+JSON.stringify(b.powerSupply.describe());for(e=0;10>e;e++)d=d.replace('"',
"");ctx.fillText(d,c.width/3,80);ctx.font="10px arial";var d;d="Shield --"+JSON.stringify(b.shield.describe());for(e=0;10>e;e++)d=d.replace('"',"");ctx.fillText(d,c.width/3,100);ctx.fillText("Weapons --",c.width/3,120);for(var f=0;f<b.weapons.length;f++){d=JSON.stringify(b.weapons[f].describe());for(e=0;10>e;e++)d=d.replace('"',"");ctx.fillText(d,c.width/3,140+20*f)}ctx.restore()};
var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");
var Weapon=function(a,b,c,d,e,f,g,m,l,n,k){a=void 0===a?10:a;b=void 0===b?1:b;c=void 0===c?1E3:c;d=void 0===d?10:d;e=void 0===e?10:e;f=void 0===f?1:f;m=void 0===m?0:m;l=void 0===l?!1:l;n=void 0===n?100:n;k=void 0===k?0:k;this.firing=this.enabled=this.turret=!1;this.rateOfFire=void 0===g?8:g;this.lockDown=!1;this.position=new Point(0,0);this.center=new Point(0,0);this.direction=new Vector(0,0);this.projectileVelocity=a;this.projectileWidth=b;this.range=c;this.limit=d;this.mass=f;this.damage=e;this.hasAmmo=
l;this.energyUsage=k;this.sound=null;this.timeOutArray=[];this.timeOutId=0;this.timeOutSound=function(){null!=this.sound&&(this.timeOutArray[this.timeOutId].currentTime=0,this.timeOutArray[this.timeOutId].play(),this.timeOutId++,this.timeOutId%=this.timeOutLimit)};this.timeOutLimit=3;this.loadSounds=function(a){for(var h=0;h<this.timeOutLimit;h++){var b=document.createElement("audio");b.src=a.src;b.volume=a.volume;this.timeOutArray[h]=b}};this.updateVolume=function(a){if(null!=this.sound)for(var h=
0;h<this.timeOutLimit;h++)this.timeOutArray[h].volume=a};this.ammo=l?n:1;0<k&&(this.powerSupply=new EnergySource(0,0));this.turnRate=0;this.projectileHeight=2*this.projectileVelocity;this.projectiles=[];this.describe=function(){var a=[];a.push("Name: "+this.name,"Damage: "+this.damage,"Rate Of Fire: "+this.rateOfFire,"Range: "+this.range,this.hasAmmo?"Ammo: "+this.ammo:"Energy Usage: "+this.energyUsage,this.turret?"Turret: yes":"Turret: no");return a};this.setTurnRate=function(a){this.turnRate=a};
this.setTurretMode=function(a){this.turret=a};this.setOwner=function(a){this.owner=a};this.setPosition=function(a){this.position=a};this.setCenter=function(a){this.center=a};this.setPowerSupply=function(a){this.powerSupply=a};this.getValue=function(){var a;this.type="l";a=20*this.damage;a=this.hasAmmo?a-this.ammo/500:a-this.energyUsage;a-=this.limit;this.turret&&(a*=4);return Math.round(a)};this.updateDirection=function(){calculateVector(this.position,this.center,this.direction);unitVector(this.direction,
this.direction);this.turret&&(this.direction.x*=-1,this.direction.y*=-1)};this.updateFiring=function(a){if(!(this.projectiles.length>=this.limit||0==this.firing||1==this.lockDown||0>=this.ammo)){if(0<this.energyUsage){if(this.powerSupply.current<this.energyUsage)return;this.powerSupply.drain(k)}null!=this.sound&&this.timeOutSound();this.lockDown=!0;a=new Rect(this.position.x,this.position.y-this.projectileHeight/2,this.projectileWidth,this.projectileHeight,this.direction.x,this.direction.y,this.projectileVelocity+
a,0);a.hit=!1;a.mass=this.mass;a.duration=this.range/this.velocity;yAxis=new Vector(0,1);var b=angleVectors(this.direction,yAxis);this.turret?this.position.x<this.center.x&&(b*=-1):this.position.x>this.center.x&&(b*=-1);rotatePolygon(a,radiansToDegrees(b));a.spin=m;a.duration=this.range/this.projectileVelocity;this.projectiles.push(a);this.hasAmmo&&this.ammo--;this.resetLockDown(this)}};this.fire=function(a){this.firing=a};this.updateDuration=function(){for(var a=0;a<this.projectiles.length;a++)this.projectiles[a].duration--,
0>=this.projectiles[a].duration&&this.projectiles.splice(a,1)};this.autoFire=function(){this.firing=1==this.firing?!1:!0};this.resetLockDown=function(a){setTimeout(function(){a.lockDown=!1},1E3/this.rateOfFire)};this.rotateAtBorder=function(a,b){if("x"==a){rotatingVersor=new Vector(-b.versor.x,b.versor.y);var c=angleVectors(b.versor,rotatingVersor),c=radiansToDegrees(c);0<rotatingVersor.y&&(c*=-1);0<rotatingVersor.x&&(c*=-1)}else"y"==a&&(rotatingVersor=new Vector(b.versor.x,-b.versor.y),c=angleVectors(b.versor,
rotatingVersor),c=radiansToDegrees(c),0>rotatingVersor.x&&(c*=-1),0<rotatingVersor.y&&(c*=-1));rotatePolygon(b,c)};this.onHit=function(a){a.sufferDamage(this.damage)};this.removeProjectiles=function(){for(var a=0;a<this.projectiles.length;a++)1==this.projectiles[a].hit&&(this.projectiles.splice(a,1),a--)};this.draw=function(){this.drawCannon();if(void 0!=this.owner)for(var a=0;a<this.projectiles.length;a++)drawPolygon(this.projectiles[a],strokeColor=this.owner.primaryColor,hitColor=this.owner.secondaryColor,
joints=!0,center=!1,fillColor=this.owner.secondaryColor,centerColor=this.owner.secondaryColor,jointColor=this.owner.secondaryColor);else for(a=0;a<this.projectiles.length;a++)drawPolygon(this.projectiles[a])};this.drawCannon=function(a){a=void 0===a?"#000FFF":a;void 0!=this.owner&&(a=this.owner.secondaryColor);ctx.beginPath();ctx.lineWidth=2;ctx.strokeStyle=a;0==this.turret?(ctx.moveTo(this.center.x,this.center.y),ctx.lineTo(this.center.x+20*this.direction.x,this.center.y+20*this.direction.y)):(ctx.moveTo(this.position.x,
this.position.y),ctx.lineTo(this.position.x+20*this.direction.x,this.position.y+20*this.direction.y));ctx.stroke()}};
function drawHeavyBlaster(a,b,c,d,e,f,g){b=void 0===b?"#0000FF":b;c=void 0===c?"#FF0000":c;d=void 0===d?!0:d;e=void 0===e?!0:e;f=void 0===f?"#00F0FF":f;g=void 0===g?"#0000FF":g;ctx.save();ctx.beginPath();ctx.lineWidth=4;ctx.strokeStyle=1==a.hit?c:b;ctx.moveTo(a.vertices[0].x,a.vertices[0].y);ctx.lineTo(a.vertices[3].x,a.vertices[3].y);ctx.moveTo(a.vertices[1].x,a.vertices[1].y);ctx.lineTo(a.vertices[2].x,a.vertices[2].y);ctx.stroke();ctx.fillStyle=g;if(d)for(b=0;b<a.vertices.length;b++)ctx.beginPath(),
ctx.arc(a.vertices[b].x,a.vertices[b].y,3,0,2*Math.PI),ctx.fill();e&&void 0!=a.center&&(ctx.fillStyle=f,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,3,0,2*Math.PI),ctx.fill());ctx.restore()}
function machineGun(){cannon=new Weapon(velocity=8,width=1,range=200,limit=12,damage=6,mass=100,rateOfFire=16,spin=0,hasAmmo=!0,ammo=2E3);cannon.type="p";cannon.name="Machine Gun";cannon.sound=document.createElement("audio");cannon.sound.src="soundEffects/machine_gun.mp3";cannon.sound.volume=.1;cannon.loadSounds(cannon.sound);return cannon}
function lightCannon(){cannon=new Weapon(velocity=2,width=4,range=250,limit=10,damage=10,mass=100,rateOfFire=8,spin=120,hasAmmo=!0,ammo=1E3);cannon.projectileVelocity=10;cannon.type="p";cannon.name="Light Cannon";return cannon}function heavyCannon(){cannon=new Weapon(velocity=4,width=8,range=280,limit=10,damage=20,mass=1E3,rateOfFire=4,spin=120,hasAmmo=!0,ammo=500);cannon.projectileVelocity=10;cannon.type="p";cannon.name="Heavy Cannon";return cannon}
function asteroidShooter(){cannon=new Weapon(velocity=10,width=20,range=280,limit=1,damage=50,mass=1E4,rateOfFire=1,spin=120,hasAmmo=!0,ammo=50);cannon.projectileVelocity=10;cannon.type="p";cannon.name="Asteroid Shooter";return cannon}
function lightLaserBlaster(){blaster=new Weapon(velocity=30,width=1,range=400,limit=12,damage=5,mass=1,rateOfFire=12,spin=0,hasAmmo=!1,ammo=1,energyUsage=5);blaster.type="p";blaster.draw=function(){void 0!=this.owner&&(color=this.owner.secondaryColor,ctx.beginPath(),ctx.lineWidth=2,ctx.strokeStyle=color,0==this.turret?(ctx.moveTo(this.center.x,this.center.y),ctx.lineTo(this.center.x+20*this.direction.x,this.center.y+20*this.direction.y)):(ctx.moveTo(this.position.x,this.position.y),ctx.lineTo(this.position.x+
20*this.direction.x,this.position.y+20*this.direction.y)),ctx.stroke());if(void 0==blaster.owner)for(var a=0;a<this.projectiles.length;a++)drawPolygon(this.projectiles[a],strokeColor="#0000FF",hitColor="#0FF0FF",joints=!1,center=!1,fillColor="#0F00FF");else for(a=0;a<this.projectiles.length;a++)drawPolygon(this.projectiles[a],strokeColor=this.owner.primaryColor,hitColor=this.owner.secondaryColor,joints=!1,center=!1,fillColor="#0F00FF")};blaster.name="Light Laser Blaster";blaster.sound=document.createElement("audio");
blaster.sound.src="soundEffects/Laser_Shoot.mp3";blaster.sound.volume=.5;blaster.loadSounds(blaster.sound);return blaster}
function heavyLaserBlaster(){blaster=new Weapon(velocity=30,width=8,range=400,limit=8,damage=20,mass=1,rateOfFire=6,spin=0,hasAmmo=!1,ammo=1,energyUsage=20);blaster.type="p";blaster.draw=function(){void 0!=this.owner&&(color=this.owner.secondaryColor,ctx.beginPath(),ctx.lineWidth=this.projectileWidth,ctx.strokeStyle=color,0==this.turret?(ctx.moveTo(this.center.x,this.center.y),ctx.lineTo(this.center.x+10*this.direction.x,this.center.y+10*this.direction.y)):(ctx.moveTo(this.position.x,this.position.y),
ctx.lineTo(this.position.x+10*this.direction.x,this.position.y+10*this.direction.y)),ctx.stroke());if(void 0==blaster.owner)for(var a=0;a<this.projectiles.length;a++)drawHeavyBlaster(this.projectiles[a],strokeColor="#0000FF",hitColor="#0FF0FF",joints=!1,center=!1,fillColor="#0F00FF");else for(a=0;a<this.projectiles.length;a++)drawHeavyBlaster(this.projectiles[a],strokeColor=this.owner.primaryColor,hitColor=this.owner.secondaryColor,joints=!1,center=!1,fillColor="#0F00FF")};blaster.name="Heavy Laser Blaster";
blaster.sound=document.createElement("audio");blaster.sound.src="soundEffects/Laser_Shoot2.mp3";blaster.sound.volume=.5;blaster.loadSounds(blaster.sound);return blaster}
function lightLaserBeam(){beam=new Weapon(velocity=100,width=2,range=800,limit=1,damage=1,mass=1,rateOfFire=1E3,spin=0,hasAmmo=!1,ammo=1,energyUsage=4);beam.type="l";beam.draw=function(){ctx.beginPath();ctx.strokeStyle=void 0==this.owner?"#009099":this.owner.secondaryColor;oldWidth=ctx.lineWidth;ctx.lineWidth=this.projectileWidth;for(var a=0;a<this.projectiles.length;a++)ctx.moveTo(this.position.x,this.position.y),ctx.lineTo(this.projectiles[a].vertices[3].x,this.projectiles[a].vertices[3].y);ctx.stroke();
ctx.lineWidth=oldWidth};beam.name="Light Laser Beam";return beam}
function heavyLaserBeam(){beam=new Weapon(velocity=100,width=8,range=800,limit=1,damage=5,mass=1,rateOfFire=60,spin=0,hasAmmo=!1,ammo=1,energyUsage=9);beam.type="l";beam.draw=function(){ctx.strokeStyle=void 0==blaster.owner?"#009099":this.owner.secondaryColor;ctx.beginPath();oldWidth=ctx.lineWidth;ctx.lineWidth=beam.projectileWidth;for(var a=0;a<this.projectiles.length;a++)ctx.moveTo(this.position.x,this.position.y),ctx.lineTo(this.projectiles[a].vertices[3].x,this.projectiles[a].vertices[3].y);ctx.stroke();
ctx.lineWidth=oldWidth};beam.name="Heavy Laser Beam";return beam}function killProjectile(a){a.duration=0}function buildWeaponsStatus(a){for(var b=[],c=0;c<a.length;c++)string=a[c].enabled?a[c].name+": enabled":a[c].name+": disabled",a[c].hasAmmo&&(string+=" --- Ammo: "+a[c].ammo),b.push(string);return b}function drawWeaponsStatus(a,b){b=void 0===b?"#00F0FF":b;ctx.beginPath();ctx.fillStyle=b;ctx.font="14px Arial";for(var c=0,d=0;d<a.length;d++)0==d%3&&(c+=240),ctx.fillText(a[d],c-230,40+d%3*20)}
function drawShipWeapons(a){for(var b=0;b<a.weapons.length;b++)a.weapons[b].draw()}
function checkProjectilesBorder(a){for(u=0;u<a.weapons.length;u++)for(var b=0;b<a.weapons[u].projectiles.length;b++)a.weapons[u].projectiles[b].update(),"p"==a.weapons[u].type?checkBorder(a.weapons[u].projectiles[b],function(){a.weapons[u].rotateAtBorder(axis,a.weapons[u].projectiles[b])}):"l"==a.weapons[u].type&&(projectile=a.weapons[u].projectiles[b],checkBorder(projectile)&&killProjectile(projectile)),rotatePolygon(a.weapons[u].projectiles[b],a.weapons[u].projectiles[b].spin)};
var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];f in d||(d[f]={});d=d[f]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,d,e){var b=this.length||0;0>d&&(d=Math.max(0,b+d));if(null==e||e>b)e=b;e=Number(e);0>e&&(e=Math.max(0,b+e));for(d=Number(d||0);d<e;d++)this[d]=a;return this}},"es6-impl","es3");
var Stellar=function(a,b,d,e){d=void 0===d?c.width/2:d;e=void 0===e?c.height/2:e;a=new Ship(d,e,20,void 0===a?"#000FFF":a,void 0===b?"#0FF0FF":b);a.name="Stellar";a.updateDirection();a.hull=new Hull(100,0);a.shield=new Shield(50,0,5,1,300);a.acceleration=.21;a.turnRate=5;a.shield.setPowerSupply(a.powerSupply);a.shield.setEnabled(!0);a.addWeapon(machineGun());a.changeWeapon();a.weapon.setOwner(a);a.weapon.setCenter(a.hitbox.vertices[0]);a.weapon.setPosition(a.auxHitbox.vertices[0]);a.weapon.enabled=
!0;a.addWeapon(machineGun());a.changeWeapon();a.weapon.setOwner(a);a.weapon.setCenter(a.hitbox.vertices[1]);a.weapon.setPosition(a.auxHitbox.vertices[1]);a.weapon.enabled=!0;a.addWeapon(lightLaserBlaster());a.changeWeapon();a.weapon.setOwner(a);a.weapon.setPowerSupply(a.powerSupply);a.weapon.setPosition(a.hitbox.center);a.weapon.setCenter(coord);a.weapon.setTurretMode(!0);a.weapon.enabled=!0;return a},Gargatuan=function(a,b,d,e){d=void 0===d?c.width/2:d;e=void 0===e?c.height/2:e;a=new Ship(d,e,30,
void 0===a?"#0000FF":a,void 0===b?"#0FF0FF":b);a.name="Gargantuan";a.updateDirection();a.hull=new Hull(200,1);a.shield=new Shield(300,0,20,.5,300);a.powerSupply=new EnergySource(1E3,20,100);a.shield.setPowerSupply(a.powerSupply);a.shield.setEnabled(!0);a.acceleration=.08;a.maxSpeed=7;a.turnRate=4;a.addWeapon(heavyLaserBlaster());a.changeWeapon();a.weapon.setOwner(a);a.weapon.setPowerSupply(a.powerSupply);a.weapon.setCenter(a.hitbox.vertices[0]);a.weapon.setPosition(a.auxHitbox.vertices[0]);a.weapon.enabled=
!0;a.addWeapon(heavyLaserBlaster());a.changeWeapon();a.weapon.setOwner(a);a.weapon.setCenter(a.hitbox.vertices[1]);a.weapon.setPosition(a.auxHitbox.vertices[1]);a.weapon.setPowerSupply(a.powerSupply);a.weapon.enabled=!0;a.addWeapon(heavyLaserBeam());a.changeWeapon();a.weapon.setOwner(a);a.weapon.setPowerSupply(a.powerSupply);a.weapon.setPosition(a.front);a.weapon.setCenter(a.hitbox.center);a.weapon.enabled=!0;return a},Colossal=function(a,b,d,e){d=void 0===d?c.width/2:d;e=void 0===e?c.height/2:e;
a=new Ship(d,e,50,void 0===a?"#0000FF":a,void 0===b?"#0FF0FF":b);a.name="Colossal";a.updateDirection();a.hull=new Hull(1E3,1);a.shield=new Shield(2E3,0,50,1,150);a.powerSupply=new EnergySource(2E3,20,100);a.shield.setPowerSupply(a.powerSupply);a.shield.setEnabled(!0);a.acceleration=.04;a.maxSpeed=9;for(b=a.turnRate=2;b<a.hitbox.vertices.length;b++)a.addWeapon(heavyLaserBlaster()),a.changeWeapon(),a.weapon.setOwner(a),a.weapon.setPowerSupply(a.powerSupply),a.weapon.setCenter(a.hitbox.vertices[b]),
a.weapon.setPosition(a.auxHitbox.vertices[b]),a.weapon.enabled=!0;for(b=0;b<a.hitbox.vertices.length-1;b++)a.addWeapon(lightLaserBlaster()),a.changeWeapon(),a.weapon.setOwner(a),a.weapon.setPowerSupply(a.powerSupply),a.weapon.setCenter(coord),a.weapon.setPosition(a.hitbox.vertices[b%3]),a.weapon.setTurretMode(!0),a.weapon.enabled=!0;return a},Turret=function(a,b,d,e,f,h,g){d=void 0===d?1:d;e=void 0===e?c.width/2:e;f=void 0===f?c.height/2:f;g=void 0===g?machineGun:g;a=new Ship(e,f,void 0===h?15:h,
void 0===a?"#0000FF":a,void 0===b?"#0FF0FF":b);a.name="Turret";a.updateDirection();a.hull=new Hull(50,3);a.shield=new Shield(20,0,5,.5,300);a.powerSupply=new EnergySource(500,10,100);a.shield.setPowerSupply(a.powerSupply);a.shield.setEnabled(!0);a.acceleration=.08;a.maxSpeed=3;a.turnRate=3;if(1==d)a.addWeapon(g()),a.changeWeapon(),a.weapon.setOwner(a),a.weapon.setPowerSupply(a.powerSupply),a.weapon.setCenter(coord),a.weapon.setPosition(a.hitbox.center),a.weapon.setTurretMode(!0),a.weapon.enabled=
!0;else for(b=0;b<d;b++)a.addWeapon(g()),a.changeWeapon(),a.weapon.setOwner(a),a.weapon.setPowerSupply(a.powerSupply),a.weapon.setCenter(coord),a.weapon.setPosition(a.hitbox.vertices[b%3]),a.weapon.setTurretMode(!0),a.weapon.enabled=!0;a.draw=function(a){a=void 0===a?this.hitbox:a;ctx.save();ctx.lineWidth=3;ctx.beginPath();1==a.hit&&0==this.shield.current?(ctx.strokeStyle="#FF0000",ctx.fillStyle="#FF0000"):(ctx.strokeStyle=this.primaryColor,ctx.fillStyle=this.primaryColor);for(var b=0;b<a.vertices.length;b++)ctx.beginPath(),
ctx.moveTo(a.center.x,a.center.y),ctx.lineTo(a.vertices[b].x,a.vertices[b].y),ctx.stroke();for(b=0;b<a.vertices.length;b++)ctx.beginPath(),ctx.arc(a.vertices[b].x,a.vertices[b].y,3,0,2*Math.PI),2==b&&(ctx.fillStyle=this.secondaryColor),ctx.fill();void 0!=a.center&&(ctx.fillStyle=this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,3,0,2*Math.PI),ctx.fill());1==this.immunity&&(ctx.strokeStyle=this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,a.side+2,0,2*Math.PI),ctx.stroke());
this.shield.enabled&&0<this.shield.current&&(ctx.save(),ctx.strokeStyle=1==a.hit?this.primaryColor:this.secondaryColor,ctx.beginPath(),ctx.arc(a.center.x,a.center.y,a.side+2,0,2*Math.PI),ctx.stroke(),ctx.restore());ctx.restore()};return a};function fetchShipByName(a){if("Stellar"==a)var b=new Stellar;else"Gargantuan"==a?b=new Gargatuan:"Colossal"==a?b=new Colossal:"Turret"==a&&(b=new Turret("#000FFF","#00F0FF",3,c.width/2,c.height/2,20,lightLaserBlaster));return b};
function collideShipHitboxes(b,d,c){for(var e=0;e<d.length;e++){var a=[];a.push(b.auxHitbox);if(hit=elasticCollision(b.hitbox,d[e],a,void 0,.1))b.sufferDamage(c),d[e].sufferDamage(c)}}function collideShipShips(b,d,c){var e=[];e.push(b.auxHitbox);for(var a=0;a<d.length;a++)if(bindB=[],bindB.push(d[a].auxHitbox),hit=elasticCollision(b.hitbox,d[a].hitbox,e,bindB,.1))b.sufferDamage(c),d[a].sufferDamage(c)}
function collideWeaponsHitboxes(b,d){for(var c=0;c<b.weapons.length;c++)for(var e=0;e<b.weapons[c].projectiles.length;e++)for(var a=0;a<d.length;a++)smartCollision(b.weapons[c].projectiles[e],d[a],function(){b.weapons[c].onHit(d[a])})}function collideWeaponsShips(b,d){for(var c=0;c<b.weapons.length;c++)for(var e=0;e<b.weapons[c].projectiles.length;e++)for(var a=0;a<d.length;a++)smartCollision(b.weapons[c].projectiles[e],d[a].hitbox,function(){b.weapons[c].onHit(d[a])})};
function updateShip(a){a.updateDirection();a.updateStrafe();a.updatePosition();a.updateTurn();a.powerSupply.recharge(a.powerSupply);a.shield.drainEnergy(a.shield);calculateAxes(a.hitbox)}function updateHitbox(a){a.update();checkBorder(a);calculateAxes(a);rotatePolygon(a,a.spin)}
function updateEnemy(a){updateShip(a);updateWeapons(a);checkBorder(a.hitbox,function(){a.auxHitbox.applyVector(diff);a.engineOn?(a.engineOn=!1,a.reverseEngineOn=!0):(a.engineOn=!0,a.reverseEngineOn=!1)});collideShipHitboxes(a,objects);updateShipProjectiles(a);checkProjectilesBorder(a)}function updateWeaponsAxes(a){for(var b=0;b<a.weapons.length;b++)for(var c=0;c<a.weapons[b].projectiles.length;c++)calculateAxes(a.weapons[b].projectiles[c])}
function updateShipProjectiles(a){for(var b=0;b<a.weapons.length;b++)a.weapons[b].updateDuration(),a.weapons[b].removeProjectiles()}function updateWeaponsShooting(a){for(var b=0;b<a.weapons.length;b++)a.weapons[b].updateDirection(),a.weapons[b].enabled&&a.weapons[b].updateFiring(a.hitbox.velocity)}function updateWeapons(a){updateWeaponsShooting(a);updateWeaponsAxes(a)}
function displayShip(a){a.updateDirection();a.updateStrafe();a.updatePosition();a.updateTurn();a.powerSupply.recharge(a.powerSupply);a.shield.drainEnergy(a.shield);for(var b=0;b<a.weapons.length;b++)a.weapons[b].updateVolume(.1),a.weapons[b].firing=!0,a.weapons[b].updateDirection(),a.weapons[b].enabled&&a.weapons[b].updateFiring(a.hitbox.velocity);for(b=0;b<a.weapons.length;b++)a.weapons[b].updateDuration(),a.weapons[b].removeProjectiles();for(c=0;c<a.weapons.length;c++)for(b=0;b<a.weapons[c].projectiles.length;b++)a.weapons[c].projectiles[b].update(),
projectile=a.weapons[c].projectiles[b],checkBorder(projectile)&&killProjectile(projectile),rotatePolygon(a.weapons[c].projectiles[b],a.weapons[c].projectiles[b].spin);for(var c=0;c<a.weapons.length;c++)for(b=0;b<a.weapons[c].projectiles.length;b++)calculateAxes(a.weapons[c].projectiles[b]),a.weapons[c].draw();a.draw()};
var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[e]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,b,c){if(e){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var d=a[c];d in b||(b[d]={});b=b[d]}a=a[a.length-1];c=b[a];e=e(c);e!=c&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,b,c){var d=this.length||0;0>b&&(b=Math.max(0,d+b));if(null==c||c>d)c=d;c=Number(c);0>c&&(c=Math.max(0,d+c));for(b=Number(b||0);b<c;b++)this[b]=a;return this}},"es6-impl","es3");
var Button=function(a,e,b,c,d){this.x=a;this.y=e;this.width=b;this.height=c;this.string=void 0===d?" ":d;this.bgColor="#FFFFFF";this.fontColor="#000000";this.onClick=function(){};this.onHover=function(){this.bgColor="#666666"};this.draw=function(){ctx.fillStyle=this.bgColor;ctx.fillRect(this.x,this.y,this.width,this.height);ctx.fillStyle=this.fontColor;ctx.font="14px arial";ctx.fillText(this.string,this.x+this.width/10,this.y+this.height/2)};this.reset=function(){this.bgColor="#FFFFFF"}},CircularButton=
function(a,e,b,c,d){this.x=a;this.y=e;this.radius=b;this.color=c;this.string=d;this.onClick=function(){};this.draw=function(){ctx.fillStyle=this.color;ctx.beginPath();ctx.arc(this.x,this.y,this.radius,0,2*Math.PI);ctx.fill();ctx.fillStyle="#000000";ctx.font="14px arial";ctx.fillText(d,this.x-this.radius/6,this.y+this.radius/10)}};
function getCookie(b){b+="=";for(var d=decodeURIComponent(document.cookie).split(";"),c=0;c<d.length;c++){for(var a=d[c];" "==a.charAt(0);)a=a.substring(1);if(0==a.indexOf(b))return a.substring(b.length,a.length)}return""}function setCookie(b,d,c){var a=new Date;a.setTime(a.getTime()+864E5*c);c="expires="+a.toUTCString();document.cookie=b+"="+d+";"+c+";path=/"}var deleteCookie=function(b){document.cookie=b+"=;expires=Thu, 01 Jan 1970 00:00:01 GMT;"};
updateResEvent=function(a){window.addEventListener("resize",function(b){a.width=window.innerWidth-20;a.height=window.innerHeight-20})};
var Score=function(a){void 0==a&&(a="#000FFF");this.coins=this.max=this.player=0;this.getMax=function(){this.max=getCookie("maxScore");0==this.max.length&&(setCookie("maxScore",0,365),this.max=getCookie("maxScore"));this.max=Number(this.max)};this.getCoins=function(){this.coins=getCookie("coins");0==this.coins.length&&(setCookie("coins",0,365),this.coins=getCookie("coins"));this.coins=Number(this.coins)};this.draw=function(a){ctx.beginPath();ctx.fillStyle=a;ctx.font="14px Arial";string="Score: "+
this.player;ctx.fillText(string,c.width/2-40,c.height-20);string="Max Score: "+this.max;ctx.fillText(string,c.width/2-160,c.height-20)}};
function generateAsteroids(a,b,d,f,h,e){for(i=0;i<h;i++)rect=new randomRect(a,b,d,f),rect.hp=Math.round(Math.sqrt(rect.mass)),rect.dead=!1,rect.sufferDamage=asteroidSufferDamage,rect.value=Math.round(rect.hp/40),objects.push(rect);for(i=0;i<e;i++)triangle=new randomTriangle(a,b,d,f),triangle.hp=Math.round(Math.sqrt(triangle.mass)),triangle.dead=!1,triangle.sufferDamage=asteroidSufferDamage,triangle.value=Math.round(triangle.hp/40),objects.push(triangle)}
function generateTurrets(a,b,d,f){d=void 0===d?!1:d;f=void 0===f?1:f;for(var h=0;h<a;h++){var e=Math.random()*c.width,g=Math.random()*c.height;myRandom=Math.random();.9<myRandom?(turret=new Turret("#FFFFFF","#FF0000",b,e,g,20,heavyLaserBlaster),turret.hitbox.spin=20):.8<myRandom?turret=Turret("#FFFFFF","#FF0000",b,e,g,20,asteroidShooter):.7<myRandom?turret=Turret("#FFFFFF","#FF0000",b,e,g,20,heavyCannon):.6<myRandom?(turret=new Turret("#FFFFFF","#FF0000",b,e,g,20,lightLaserBlaster),turret.hitbox.spin=
20):turret=.5<myRandom?Turret("#FFFFFF","#FF0000",b,e,g,20,lightCannon):Turret("#FFFFFF","#FF0000",b,e,g,20,machineGun);for(e=0;e<b;e++)turret.weapons[e].rateOfFire*=f,turret.weapons[e].setCenter(player.hitbox.center),turret.weapons[e].setPosition(turret.hitbox.vertices[e]),turret.weapons[e].firing=!0,turret.weapons[e].sound=void 0,console.log(turret.weapons.sound);turret.weapon.setOwner(turret);d&&(turret.engineOn=!0,rotatePolygon(turret.hitbox,360*Math.random()));turret.value=Math.round(10*myRandom);
turret.value*=b;enemies.push(turret)}}
var Level=function(a){this.current=0;this.max=20;this.draw=function(a){ctx.beginPath();ctx.fillStyle=a;ctx.font="14px Arial";string="Level: "+this.current;ctx.fillText(string,c.width/2+40,c.height-20)};this.start=function(){player.setImmunity(3);12>=this.current?(player.hull.recover(10),0!=this.current%2?generateAsteroids(c.width/20+2*this.current,c.width/100+2*this.current,Math.round(.7*this.current),Math.floor(.2*this.current),Math.round(.6*this.current),Math.round(.4*this.current)):generateTurrets(Math.floor(this.current/
2),1,!0,.25)):13<=this.current&&15>=this.current?generateTurrets(Math.floor(this.current/3),2,!0,.5):generateTurrets(Math.floor(this.current/4),3,!0,.75)};this.next=function(){this.current++}};
function buildInstructions(){var a=[];a.push("W/UpArrow: Main Engine Throttle");a.push("X: Reverse Engine Throttle");a.push("A/LeftArrow: Left turning");a.push("D/RightArrow: Right turning");a.push("Q: Left strafe");a.push("E: Right strafe");a.push("S/DownArrow: Brake");a.push("V/Mouse Click: Shoot");a.push("C: Auto-Fire");a.push("R: Cycle Weapons");a.push("F: Enable Shield");a.push("T: Auto-pilot");a.push("Esc: Cancel auto-pilot");a.push(",: Decrease volume");a.push(".: Increase volume");return a}
function drawInstructions(a,b){b=void 0===b?"#000FFF":b;ctx.save();ctx.beginPath();ctx.fillStyle="#000000";ctx.fillRect(0,0,c.width,c.height/4);ctx.fillStyle=b;ctx.font="14px Arial";for(var d=0,f=0;f<a.length;f++)0==f%5&&(d+=240),ctx.fillText(a[f],d-230,40+f%5*20);ctx.restore()}
function drawEndGame(a,b,d){b=void 0===b?"#000FFF":b;d=void 0===d?"#FF0000":d;a?(ctx.beginPath(),ctx.fillStyle=b,ctx.font="28px Arial",ctx.fillText("Congratulations! You've survived!",c.width/6,c.height/2)):(ctx.beginPath(),ctx.fillStyle=d,ctx.font="28px Arial",ctx.fillText("You've died! Press ESC to restart.",c.width/3,c.height/2))}function killObjects(a){for(i=0;i<a.length;i++)1==a[i].dead&&(score.player+=a[i].value,a.splice(i,1))}
function drawAsteroid(a,b,d){b=void 0===b?"#FFFFFF":b;d=void 0===d?"#FF0000":d;ctx.save();ctx.beginPath();ctx.lineWidth=3;ctx.strokeStyle=1==a.hit?d:b;ctx.moveTo(a.vertices[0].x,a.vertices[0].y);for(b=0;b<a.vertices.length;b++)ctx.lineTo(a.vertices[b].x,a.vertices[b].y);ctx.lineTo(a.vertices[0].x,a.vertices[0].y);ctx.stroke();ctx.restore()}function asteroidSufferDamage(a){this.hp-=a;0>this.hp&&(this.dead=!0)}
function drawLobbyBackground(){ctx.fillStyle="#000000";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#FFFFFF";ctx.font="28px arial";ctx.fillText("Select your ship",20,40)}
function buildLobbyButtons(a){myButton=new Button(20,200,150,50,"Stellar");myButton.onClick=function(){player=new Stellar(primaryColor,secondaryColor,c.width/2,c.height/2+150);selected=!0};a.push(myButton);myButton=new Button(20,260,150,50,"Gargantuan");myButton.onClick=function(){player=new Gargatuan(primaryColor,secondaryColor,c.width/2,c.height/2+150);selected=!0};a.push(myButton);myButton=new Button(20,320,150,50,"Turret");myButton.onClick=function(){player=new Turret("#000FFF","#00F0FF",3,c.width/
2,c.height/2+150,20,lightLaserBlaster);selected=!0};a.push(myButton);myButton=new Button(20,380,150,50,"Colossal");myButton.onClick=function(){player=new Colossal(primaryColor,secondaryColor,c.width/2,c.height/2+150);selected=!0};a.push(myButton);myButton=new Button(20,100,200,50,"Coins: "+score.coins);myButton.onHover=function(){};a.push(myButton);new Point(c.width/2,c.height/2);var b=[];b.push(new Stellar);b.push(new Gargatuan);b.push(new Turret("#000FFF","#00F0FF",3,c.width/2,c.height/2,20,lightLaserBlaster));
b.push(new Colossal);for(var d=1;d<b.length;d++)a[d].string+=": "+b[d].getValue();b=[];confirmButton=new Button(c.width/2-100,c.height-100,200,50,"Confirm");confirmButton.onClick=function(){"Stellar"==player.name&&(confirmed=!0);score.coins>player.getValue()&&(confirmed=!0)}}
function selectShipLoop(){drawLobbyBackground();window.selected&&(window.displaying||(window.buttons.push(confirmButton),window.displaying=!0),displayShip(player),drawStats(player));for(var a=0;a<buttons.length;a++)window.buttons[a].draw();confirmed?(c.removeEventListener("touchstart",buttonModeClick,!1),c.removeEventListener("click",function(a){buttonModeClick(a)},!1),c.addEventListener("click",function(a){mouseClick(a)},!1),c.addEventListener("touchstart",pegaCoordenadasMobile,!1),window.buttons=
[],c.width=window.innerWidth-20,c.height=window.innerHeight-20,updateResEvent(c),player=fetchShipByName(player.name),window.playing=!0,window.rewarded=!1,selectMusic.pause(),music=document.getElementById("loopA"),music.play(),music.addEventListener("ended",function(){this.currentTime=0;this.play()},!1),requestAnimationFrame(mainLoop)):requestAnimationFrame(selectShipLoop)}
function mainLoop(){newDate=new Date;elapsedTime=newDate-lastDate;lastDate=new Date;fps.add(elapsedTime);ctx.fillStyle="#000000";ctx.fillRect(0,0,c.width,c.height);0==objects.length&&0==enemies.length&&level.current<=level.max&&(level.next(),level.current<=level.max&&level.start());for(var a=0;a<objects.length;a++)updateHitbox(objects[a]);if(player.dead)drawEndGame(!1),score.max<score.player&&setCookie("maxScore",score.player,365),window.rewarded||(score.coins+=30*score.player,setCookie("coins",score.coins,
365),window.rewarded=!0);else{updateShip(player);updateWeapons(player);var b=[];b.push(player);for(a=0;a<enemies.length;a++)updateEnemy(enemies[a]),collideWeaponsShips(enemies[a],b);collideWeaponsHitboxes(player,objects);collideWeaponsShips(player,enemies);checkBorder(player.hitbox,function(){player.auxHitbox.applyVector(diff)})}level.current>level.max&&(drawEndGame(!0),score.max<score.player&&setCookie("maxScore",score.player,365),window.rewarded||(score.coins+=30*score.player,setCookie("coins",
score.coins,365),window.rewarded=!0));collideShipHitboxes(player,objects,COLLISION_DAMAGE);collideShipShips(player,enemies,COLLISION_DAMAGE);updateShipProjectiles(player);checkProjectilesBorder(player);player.autoPilot();player.drawStatus();instruct?drawInstructions(instructions,player.secondaryColor):(weaponStatus=buildWeaponsStatus(player.weapons),drawWeaponsStatus(weaponStatus,player.secondaryColor));for(a=0;a<objects.length;a++)drawAsteroid(objects[a]);for(a=0;a<enemies.length;a++)enemies[a].draw(),
drawShipWeapons(enemies[a]);0==player.dead&&(drawShipWeapons(player),player.drawAutoPath(),player.draw());killObjects(objects);killObjects(enemies);checkColisionsNaive(objects);score.draw(player.secondaryColor);level.draw(player.secondaryColor);fps.calculateMean();drawFPS(fps.mean,player.secondaryColor);window.playing?setTimeout(function(){requestAnimationFrame(mainLoop)},interval):(window.buttons=[],buildLobbyButtons(window.buttons),window.instruct=!1,window.selected=!1,window.displaying=!1,window.confirmed=
!1,window.playing=!1,level.current=0,score.player=0,objects=[],enemies=[],music.pause(),selectMusic.play(),requestAnimationFrame(selectShipLoop))}selectMusic=document.getElementById("selectLoop");selectMusic.play();selectMusic.addEventListener("ended",function(){this.currentTime=0;this.play()},!1);selectMusic.volume=.5;console.log(selectMusic);ctx.lineWidth=3;
var j=0,primaryColor="#000FFF",secondaryColor="#00F0FF",lastDate=new Date,fps=new Fps,maxFPS=1E3,interval=1E3/maxFPS,COLLISION_DAMAGE=10,camera=void 0,score=new Score;score.getMax();score.getCoins();var level=new Level,instructions=buildInstructions(),objects=[],enemies=[];window.buttons=[];buildLobbyButtons(window.buttons);window.instruct=!1;window.selected=!1;window.displaying=!1;window.confirmed=!1;window.playing=!1;var coord=new Point(c.width/2,c.height/2);selectShipLoop();
var coord=new Point(c.width/2,c.height/2);function pegaCoordenadas(a){coord.x=a.clientX;coord.y=a.clientY}function pegaCoordenadasMobile(a){coord.x=a.touches[0].clientX;coord.y=a.touches[0].clientY;player.lock=!0;for(a=0;a<player.weapons.length;a++)player.weapons[a].fire(!0);player.setupAutoPilot(coord)}
keyboardDown=function(a){"."==a.key&&1>music.volume&&(music.volume+=.1);","==a.key&&0<music.volume&&(music.volume-=.1);if("v"==a.key)for(var b=0;b<player.weapons.length;b++)player.weapons[b].fire(!0);"Escape"==a.key&&(instruct=!0,player.dead&&(playing=!1));if("c"==a.key)for(b=0;b<player.weapons.length;b++)player.weapons[b].autoFire();"r"==a.key&&player.cycleEnabledWeapons();"f"==a.key&&(player.shield.enabled?player.shield.setEnabled(!1):player.shield.setEnabled(!0));player.lock||("w"!=a.key&&"ArrowUp"!=
a.key||player.throttle(!0),"x"==a.key&&player.reverseThrottle(!0),"q"==a.key&&player.strafe("l",!0),"e"==a.key&&player.strafe("r",!0),"s"!=a.key&&"ArrowDown"!=a.key||player.brake(!0),"d"!=a.key&&"ArrowRight"!=a.key||player.turn("r",!0),"a"!=a.key&&"ArrowLeft"!=a.key||player.turn("l",!0),"t"==a.key&&(player.lock=!0,player.setupAutoPilot(coord)))};
keyboardUp=function(a){"Escape"==a.key&&(instruct=!1,player.lock&&(player.lock=!1));if("v"==a.key)for(var b=0;b<player.weapons.length;b++)player.weapons[b].fire(!1);player.lock||("w"!=a.key&&"ArrowUp"!=a.key||player.throttle(!1),"x"==a.key&&player.reverseThrottle(!1),"q"==a.key&&player.strafe("l",!1),"e"==a.key&&player.strafe("r",!1),"s"!=a.key&&"ArrowDown"!=a.key||player.brake(!1),"d"!=a.key&&"ArrowRight"!=a.key||player.turn("r",!1),"a"!=a.key&&"ArrowLeft"!=a.key||player.turn("l",!1))};
buttonModeClick=function(){if(void 0!=buttons)for(var a=0;a<buttons.length;a++){var b=buttons[a].x+buttons[a].width,d=buttons[a].y,e=buttons[a].y+buttons[a].height;if(coord.x>buttons[a].x&&coord.x<b&&coord.y>d&&coord.y<e)buttons[a].onClick()}};buttonModeHover=function(){if(void 0!=buttons)for(var a=0;a<buttons.length;a++){var b=buttons[a].x+buttons[a].width,d=buttons[a].y,e=buttons[a].y+buttons[a].height;if(coord.x>buttons[a].x&&coord.x<b&&coord.y>d&&coord.y<e)buttons[a].onHover();else buttons[a].reset()}};
function mouseDown(){for(var a=0;a<player.weapons.length;a++)player.weapons[a].fire(!0)}function mouseUp(){for(var a=0;a<player.weapons.length;a++)player.weapons[a].fire(!1)}window.addEventListener("keydown",function(a){keyboardDown(a)},!1);window.addEventListener("keyup",function(a){keyboardUp(a)},!1);c.addEventListener("mousemove",pegaCoordenadas,!1);c.addEventListener("mousemove",buttonModeHover,!1);c.addEventListener("touchstart",buttonModeClick,!1);c.addEventListener("mousedown",mouseDown,!1);
c.addEventListener("mouseup",mouseUp,!1);c.addEventListener("click",function(a){buttonModeClick(a)},!1);
</script>
</body>
</body>

</html>
